### PR TITLE
Small fix for a procedure step

### PR DESCRIPTION
**Pull request by rh-max**
#### What changes are you introducing?

A consistency fix for a step in a procedure.

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

https://issues.redhat.com/browse/SAT-28627

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.13/Katello 4.15 (Satellite 6.17)
* [ ] Foreman 3.12/Katello 4.14 (Satellite 6.16)
* [ ] Foreman 3.11/Katello 4.13 (orcharhino 6.11 on EL8 only)
* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

### CODE REVIEW

**Review by maximiliankolb — COMMENTED** [review]
The "Actions" menu is on the "Virtual Machines" tab which is not selected by default.

**Review by apinnick — DISMISSED** [review]

**Review by maximiliankolb — APPROVED** [review]
LGTM; verified on Foreman 3.12.

**Comment by rh-max** [comment]
Thanks @maximiliankolb . If no further feedback, could you please merge?

**Comment by maximiliankolb** [comment]
Taking this screenshot as tech review:

image

**Comment by maximiliankolb** [comment]
Merged to "master" and cherry-picked because I have checked the wording on 3.12 and 3.11 too:
   e2d6d55463..765b7c0447  3.13 -> 3.13
   b82aaa7f16..dcc8bcfca1  3.12 -> 3.12
   70a9cf28c8..eb86284792  3.11 -> 3.11

**Pull request merged**
