### PR TITLE
Add link to RH Knowledgebase (SCAP) Satellite only

### PR DESCRIPTION
**Pull request by Lennonka**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4 on EL8 only)
* [ ] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [ ] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

### CODE REVIEW

**Review by maximiliankolb — APPROVED** [review]
link works!

**Comment by Lennonka** [comment]
Holding this PR until https://bugzilla.redhat.com/show_bug.cgi?id=2176122 is resolved.

**Review by mjivraja — APPROVED** [review]

**Comment by ekohl** [comment]
Converting to a draft so it's clear that it shouldn't be merged at this moment.

**Comment by Lennonka** [comment]
I've decided to merge this, because there are no immediate plans to include RHEL 9 in Satellite.
Also, I'll cherry pick it all down to 3.1.

**Comment by Lennonka** [comment]
Cherry-picked:
- faaa4c1cc..34d44bec7  3.8 -> 3.8
- 8c2e2722a..4019b6bca  3.7 -> 3.7
- 830d39b52..1cc013913  3.6 -> 3.6
- 5077568a7..54de7d58a  3.5 -> 3.5
- 058c6df91..75dfa80de  3.4 -> 3.4
- 9b19658be..f67902d68  3.3 -> 3.3
- 63234e6d7..958f9d0fb  3.2 -> 3.2
- 320c19efa..6ff936b25  3.1 -> 3.1

**Pull request merged**
