### PR TITLE
Corrected Snippets List Format

### PR DESCRIPTION
**Pull request by sabuchan07**
Fixed an incorrectly formatted list.

Cherry-pick into:

* [ ] Foreman 3.0
* For Foreman 2.5, file a separate PR request

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Hi and welcome @sabuchan07 
Can you please rebase your branch to master? Then I'm happy to have a look at your changes.

**Comment by melcorr** [comment]
Hey @maximiliankolb - @sabuchan07 is new and had forgotten to target the 2.5 branch, so I have just updated it for her. 

@sabuchan07 For future reference, please look at https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request when you want to target a branch that is not master.

**Comment by melcorr** [comment]
I checked and this is fixed on our master branch so the error is in fact only here.

**Review by melcorr — APPROVED** [review]
LGTM

**Comment by maximiliankolb** [comment]
Awesome, thanks @melcorr and @sabuchan07 !

**Pull request merged**
