### PR TITLE
Remove configuring container gateway section

### PR DESCRIPTION
**Pull request by ekohl**
This section tells users to change th configuration file, but the installer will overwrite this and revert any changes. That makes it unsupported.

Fixes: 804a2c7aa8c4db7c81d9a68fd052ef9ce5f81918 ("Add Container Gateway info")

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* [x] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [x] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

### CODE REVIEW

**Review by maximiliankolb — COMMENTED** [review]
Change looks reasonable to me. Can someone from the container team ACK?

**Review by adamlazik1 — APPROVED** [review]
LGTM

**Comment by ekohl** [comment]
@ianballou mind taking a look?

**Comment by ekohl** [comment]
a8cc9b343550..1c36fa6513bb  3.6 -> 3.6
   23ff7608b9a8..f0711921e91c  3.7 -> 3.7
   9ce3b6972883..d27b536522ab  3.8 -> 3.8

**Pull request merged**
