### PR TITLE
add CNAME file after cleanup

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by lzap** [comment]
The CNAME file was accidentally deleted. Shall we put it back into the git directly? https://github.com/theforeman/foreman-documentation/commit/ea36034da5d3f13733feeeb9a7b2995d89e4a7af

**Comment by lzap** [comment]
Wait, the commit is from `gh-pages` repo not `master`. Weird. What created it previously?

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-documentation/commit/1b33d513fe1ec6d5d4d15ee00a50cbefc50cefc2 did. Not sure how @melcorr did this, but possibly via the GH UI?

**Comment by evgeni** [comment]
Yeah, we did it in the UI.

**Comment by lzap** [comment]
I am fine if this works, unsure how to test this but feel free to merge :-)

**Comment by lzap** [comment]
I mean this can't hurt (TM)

**Comment by evgeni** [comment]
you can't really test that I'm afraid

**Pull request merged**
