### PR TITLE
Fix Certified Hypervisor link

### PR DESCRIPTION
**Pull request by mjivraja**
The current link is obsolete. Replaced the new link.

https://bugzilla.redhat.com/show_bug.cgi?id=2243681

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.8/Katello 4.10
* [X] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [X] Foreman 3.6/Katello 4.8
* [X] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [X] Foreman 3.4/Katello 4.6 (EL8 only)
* [X] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* [X] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [X] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

### CODE REVIEW

**Review by maximiliankolb — APPROVED** [review]
Link works!

**Comment by bangelic** [comment]
Was about to say LGTM and the link works but Max beat me to it! :)

**Comment by mjivraja** [comment]
> Was about to say LGTM and the link works but Max beat me to it! :)

:smile: @maximiliankolb :green_heart:

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked: :heavy_check_mark: 
   9fc2e301d..722316daa  3.8 -> 3.8
   450cfb20d..60bda02f3  3.7 -> 3.7
   cfd281cc3..610dca73d  3.6 -> 3.6
   70e102f4d..635c3fc75  3.5 -> 3.5
   a1533d620..1f40e7f19  3.4 -> 3.4
   df9da9649..7d146ba35  3.3 -> 3.3
   dcd237d94..94f13ad08  3.2 -> 3.2
   77a7dd838..379112e8f  3.1 -> 3.1

**Pull request merged**
