### PR TITLE
Remove OSTree

### PR DESCRIPTION
**Pull request by maximiliankolb**
To my understanding, it has been dropped with Katello 4.1.0. See

* https://community.theforeman.org/t/puppet-ostree-content-types-being-removed-in-katello/17817
* https://github.com/Katello/katello/commit/56668d54bc16b1bf0115918e6baf9990f32fcd98
* https://projects.theforeman.org/issues/31682

Cherry-pick into:

* [x] Foreman 3.3
* [x] Foreman 3.2
* [x] Foreman 3.1

### CODE REVIEW

**Comment by maximiliankolb** [comment]
@jlsherrill Can you please confirm merging and cherry-picking this to Foreman 3.1 documentation?

**Comment by melcorr** [comment]
> @jlsherrill Can you please confirm merging and cherry-picking this to Foreman 3.1 documentation?

@jlsherrill is working on a different RH project these days... I'll see who would be best to ask..

**Comment by evgeni** [comment]
ostree support is back starting with Katello 4.3

**Comment by melcorr** [comment]
> ostree support is back starting with Katello 4.3

This is what I had thought... 
Are we missing something @maximiliankolb ?

**Comment by maximiliankolb** [comment]
I've tested this on Foreman 3.2.0 with Katello 4.4.0.2. Do I need a separate plugin for OSTree content? Is this enabled by default?

Screenshot 2022-05-12 at 13 33 40

```
yum list installed | grep -i "ostree"
tfm-rubygem-pulp_ostree_client.noarch         2.0.0-0.1.a1.el7         @katello
```

**Comment by melcorr** [comment]
It's not enabled by default...

**Comment by melcorr** [comment]
@maximiliankolb  https://github.com/theforeman/foreman-documentation/pull/1234

**Comment by evgeni** [comment]
And only available on el8!

**Comment by maximiliankolb** [comment]
Thank you Evgeni and Melanie. Closing this PR.

**Pull request closed without merging**
