### PR TITLE
Remove unused files

### PR DESCRIPTION
**Pull request by maximiliankolb**
DO NOT cherry-pick

### CODE REVIEW

**Comment by maximiliankolb** [comment]
@Lennonka `guides/common/modules/con_how-to-use-iss-based-on-your-network-setup.adoc` is not included anywhere.

**Comment by maximiliankolb** [comment]
@ianf77 `guides/common/modules/proc_viewing-ansible-roles.adoc` is currently unused.

**Review by Lennonka — APPROVED** [review]
Syntax alright, otherwise I have to trust that you know what you're doing :)

**Comment by Lennonka** [comment]
Okay, let me check if we can remove other things...

**Comment by Lennonka** [comment]
Okay, let's just remove the two additional files that you're suggesting and we can merge.
I'm considering writing a script that would check which modules are not used -- maybe an issue?

**Comment by maximiliankolb** [comment]
> Okay, let's just remove the two additional files that you're suggesting and we can merge. I'm considering writing a script that would check which modules are not used -- maybe an issue? Edit: I've just noticed that we already have it! :D

Yes, I wrote that just last week.

**Comment by Lennonka** [comment]
@maximiliankolb Ian is no longer on this project and he's on vacation until Monday. Do we want to wait for him? I back this up.

**Comment by maximiliankolb** [comment]
> @maximiliankolb Ian is no longer on this project and he's on vacation until Monday. Do we want to wait for him? I back this up.

OK, that works for me! Merging!

**Pull request merged**
