### PR TITLE
update the FQDN when doing the doing the monitoring configuration

### PR DESCRIPTION
**Pull request by Imaanpreet**
* [x] I am okay with my commits getting squashed when you merge this PR.
* [ ] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.11/Katello 4.13
* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

### CODE REVIEW

**Comment by Imaanpreet** [comment]
Problem Statement

Here is the link

https://docs.redhat.com/en/documentation/red_hat_satellite/6.15/html-single/monitoring_satellite_performance/index#configuring-pcp-data-collection_monitoring

and here is the recommendation

```
cd /var/lib/pcp/pmdas/openmetrics
echo "https://satellite.example.com/metrics" > config.d/foreman.url
./Install 
```
 Instead, it could be something like

```
cd /var/lib/pcp/pmdas/openmetrics
echo "https://$(hostname -f)/metrics" > config.d/foreman.url
./Install 
```
 
The reason is because, in general, the customer will copy/paste the command and will move on, as consequence, the implementation will fail, once the FQDN is different.

**Comment by Lennonka** [comment]
I don't think this is a good idea, especially for API requests, because those can be run from other machines than the Foreman server.

**Review by ekohl — CHANGES_REQUESTED** [review]
Implementation note: you also didn't include `$()` so it's not clear that it is a shell command. But that's a small detail.

This is not something we should do. The `foreman-example-com` attribute is used in a very different way. For example, we say on the Capsule point it to `foreman-example-com`. If you change that to `hostname -f` then it will break.

Our convention is to use underscores to indicate a user should change the actual value.

Further looking into the future: I want to get rid of the hostname equals service name. At some point I think we should support that your server is named `satellite01.example.com` (and if it's load balanced also `satellite02.example.com`) while the service runs on `satellite.example.com`. The `foreman-example-com` attribute is supposed to be the service name, not the hostname.

**Comment by ekohl** [comment]
I'd even suggest that if you really want to do this (and that's a big if) then we should modify the procedure to avoid the attribute.

**Comment by Imaanpreet** [comment]
Hello @ekohl , @Lennonka & @maximiliankolb : thank you for looking in to the issue. 

Sorry for the typo (for not adding $ while creating the PR) @ekohl. 

Before creating the PR , I knew this we need to come to an agreement what to do with this request.  So the goal of this PR is to avoid the failure and we can do this by adding an another line as @Lennonka mentioned. I can totally agree with @ekohl avoid changing the attribute.

**Comment by maximiliankolb** [comment]
docs triage: Closing this PR. We cannot make this change as proposed: Docs and esp. attribute usage are consistent: we always have "foreman.example.com" as single FQDN for your Foreman instance.

Regarding HA/load balancing: please see https://github.com/theforeman/foreman-documentation/pull/3187#pullrequestreview-2220814483

@Imaanpreet If you have further concerns, please reopen the PR or ping us on Matrix.

**Comment by Imaanpreet** [comment]
Hello @maximiliankolb : can we just add a line by replace the satellite/foreman hostname with FQDN for example - 

"Be aware that you will need to replace the value of _{foreman-example-com}_ with the FQDN of your server"

[here](https://github.com/theforeman/foreman-documentation/blob/master/guides/common/modules/proc_configuring-pcp-data-collection.adoc?plain=1#L57)

This way we keep the hardcoded value and we don't need to change it. What are your thoughts about it?

**Comment by maximiliankolb** [comment]
@Imaanpreet Maybe some after line 63 similar to

````
# guides/common/modules/snip_replace-fqdn-projectserver.adoc
1:Replace _{foreman-example-com}_ with the FQDN of your {ProjectServer}.
````

**Comment by Imaanpreet** [comment]
> @Imaanpreet Maybe after line 63 similar to
> 
> ```
> # guides/common/modules/snip_replace-fqdn-projectserver.adoc
> 1:Replace _{foreman-example-com}_ with the FQDN of your {ProjectServer}.
> ```

looks perfect.

**Comment by Imaanpreet** [comment]
@maximiliankolb, Hello !
Have you updated the change? can I update and give you the new PR ?

**Pull request closed without merging**
