### PR TITLE
Change "OS" to "operating system" per RHSSG

### PR DESCRIPTION
**Pull request by rh-max**
#### What changes are you introducing?

Cherrypicking https://github.com/theforeman/foreman-documentation/pull/3387 into 3.12.

If successful, please also cherrypick down to 3.5, thank you.

### CODE REVIEW

**Review by maximiliankolb — APPROVED** [review]
LGTM.

**Comment by apinnick** [comment]
Try rebasing to see whether that fixes the failed Vale check.

**Comment by Lennonka** [comment]
@apinnick The Vale error seems unrelated to changes in this PR. I've tried rerunning the Vale check, but it ends up with the [same error](https://github.com/theforeman/foreman-documentation/actions/runs/11739145945/job/32957760688#step:3:30). Care to investigate? Could there be a problem on a stable branch? Either way, I haven't seen it before.

**Review by Lennonka — APPROVED** [review]

**Comment by Lennonka** [comment]
@rh-max Unfortunately, there are conflicts again on 3.11. Since it's just a style fix, it is not necessary to propagate it to older releases if everyone agrees.

**Comment by apinnick** [comment]
> @apinnick The Vale error seems unrelated to changes in this PR. I've tried rerunning the Vale check, but it ends up with the [same error](https://github.com/theforeman/foreman-documentation/actions/runs/11739145945/job/32957760688#step:3:30). Care to investigate? Could there be a problem on the stable branch? Either way, I haven't seen it before.

@Lennonka See my [comment](https://github.com/theforeman/foreman-documentation/pull/3440#issuecomment-2473003751). We fixed the error in the main repo. PRs need to be rebased to pick up the fix.

**Pull request merged**
