### PR TITLE
don't enable the repos on rhel twice

### PR DESCRIPTION
**Pull request by evgeni**
Fixes: b5fdcc05a78142212ff85da84f85de33e8e02cb4

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.5/Katello 4.7
* [x] Foreman 3.4/Katello 4.6
* [ ] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Review by maximiliankolb — APPROVED** [review]
Thanks! It's a duplicate of line 83-85 if I read the source correctly.

Also, this should have never happened, because we should only include snippets in modules, not other modules.

**Comment by evgeni** [comment]
> Thanks! It's a duplicate of line 83-85 if I read the source correctly.

Yeah, it's an oversight from the "drop EL7" PR

> Also, this should have never happened, because we should only include snippets in modules, not other modules.

I have no idea what that means, but also don't see how a different "type" of include would have fixed that -- the "double" include was there for a reason: once for el7 once for el8, it was just not correctly removed when el7 was dropped.

**Comment by ekohl** [comment]
> I have no idea what that means, but also don't see how a different "type" of include would have fixed that -- the "double" include was there for a reason: once for el7 once for el8, it was just not correctly removed when el7 was dropped.

There are different includes that we have. You may recognize `proc` (procedure) and `snip` (snippet). I think the rule is that procedures may only include snippets, not other procedures.

**Comment by evgeni** [comment]
> > I have no idea what that means, but also don't see how a different "type" of include would have fixed that -- the "double" include was there for a reason: once for el7 once for el8, it was just not correctly removed when el7 was dropped.
> 
> There are different includes that we have. You may recognize `proc` (procedure) and `snip` (snippet). I think the rule is that procedures may only include snippets, not other procedures.

Right, but renaming `proc_configuring-repositories-el.adoc` to `snip_configuring-repositories-el.adoc` wouldn't have prevented the issue at hand, no?

**Comment by ekohl** [comment]
Simply renaming probably not, no.

**Comment by evgeni** [comment]
To github.com:theforeman/foreman-documentation.git
   76f852c4a..86d7b50b2  3.4 -> 3.4
   3a66ef42a..94c9e23b9  3.5 -> 3.5

**Pull request merged**
