### PR TITLE
Add quotes to the path to render it properly

### LINKED ISSUE #668: docs.theforeman.org Foreman 3.0 web page links not rendering properly
I cannot see anything wrong in https://github.com/theforeman/foreman-documentation/commit/00de02be190de55babef8d6ac23380e7682a4a81

And path is set to 3.0, which is correct: 

https://raw.githubusercontent.com/theforeman/foreman-documentation/master/web/content/3.0.md

Yet the Foreman 3.0 page links have 3 in their path rather than 3.0: 

https://docs.theforeman.org/3.0.html

The links to 3.0 render correctly, but are not linked to: 

https://docs.theforeman.org/3/Installing_Server_on_Red_Hat/index-foreman-el.html

While this does exist: 

https://docs.theforeman.org/3.0/Installing_Server_on_Red_Hat/index-foreman-el.html

Does anyone know why?

### PR DESCRIPTION
**Pull request by melcorr**
fixes #668

I'm unsure how to test this without merging. 

Cherry-pick into:

* [x] Foreman 3.0
* [ ] Foreman 2.5 (Satellite 6.10)
* [ ] Foreman 2.4
* [ ] Foreman 2.3 (Satellite 6.9)
* [ ] Foreman 2.1 (Satellite 6.8)

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
To be consistent, shall we update all existing `web/content/2.*.md` as well? That means there are no bad examples to copy from.

**Comment by melcorr** [comment]
> To be consistent, shall we update all existing `web/content/2.*.md` as well? That means there are no bad examples to copy from.

Can I merge and test if this fixes it? Then I will do this everywhere, for sure. +1 to your suggestion.

**Comment by ekohl** [comment]
You can easily test it locally:
```console
$ cd web
$ hugo server
```
Then open the URL it mentions (http://localhost:1313/).

hugo is available in Fedora.

**Comment by melcorr** [comment]
> You can easily test it locally:
> 
> ```
> $ cd web
> $ hugo server
> ```
> 
> Then open the URL it mentions (http://localhost:1313/).
> 
> hugo is available in Fedora.

Oh, thanks so much. 
I'll add that to the readme.

**Comment by ekohl** [comment]
There's also a `Makefile` but typing `make server` is just as long as `hugo server`.

**Pull request merged**
