### PR TITLE
Move "Convert to RHEL" to separate guide

### PR DESCRIPTION
**Pull request by maximiliankolb**
Hi!
I propose the following change: Let's move the "Convert a CentOS host to RHEL" section to a separate guide, because it's not really part of any procedure to manage content.

**This should not be merged without a broader discussion to see if we're moving towards the right direction.**

### CODE REVIEW

**Comment by ekohl** [comment]
I would be in favor of more specific guides. To me the whole administration guide should be more like an administration book with multiple guides. They are standalone things

**Comment by lzap** [comment]
I would like to hear from @melcorr because we need to think about downstream products as well. Namely Red Hat has some standards. For example, RHEL has many guides indeed but I do not see necessary short guides there: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8

**Comment by maximiliankolb** [comment]
Rebased to master. 👀

**Comment by melcorr** [comment]
@maximiliankolb I would like @mdolezelova, who is getting more involved with the docs to understand this proposal before we move forward. 
I will return to this next week after ForemanCon.

**Comment by mdolezelova** [comment]
> @maximiliankolb I would like @mdolezelova, who is getting more involved with the docs to understand this proposal before we move forward. I will return to this next week after ForemanCon.

Hi @melcorr , @maximiliankolb , thank you for putting me in the loop. As I'm still in the process of taking over the DPM role on Satellite, please is there any immediate action item or any inputs needed from me or should I just wait for you, Mel, reaching out with more details (sorry, if I misunderstood the message). Just please let me know what's currently needed from my side. Thank you!

**Comment by melcorr** [comment]
@maximiliankolb  if you can wait about two weeks, I can discuss this properly and your other PR with @mdolezelova because depending on what we do, it will have consequences for Satellite documentation. If not, let me know.

**Comment by maximiliankolb** [comment]
Yes, with this particular PR, I can wait two weeks. Overall, if you get into a discussion of potentially splitting content (like moving "convert to RHEL" to a separate guide), count me in. I am generally in favour of having smaller guide. Please also have https://github.com/theforeman/foreman-documentation/pull/777 in mind.

I will ping you at the end of November again.

**Comment by maximiliankolb** [comment]
Rebased to master.

**Comment by melcorr** [comment]
@mdolezelova - this content was originally added by Ian as part of  https://issues.redhat.com/browse/SAT-3086

I'm assuming no real thought went into this as I agree with @maximiliankolb that the content is misplaced. 

Content Management Guide concerns syncing content into Foreman via the Katello plugin, and managing that content in as complex a way as your deployment requires. This is more of a host management exercise. 

I would propose that either it becomes a chapter in the Managing Hosts guide, as essentially it is about host management or it is allowed to stand alone as a guide by itself. 

I would also propose that the "Creating an Activation Key" topic is reused across the guides rather than referenced. I think @maximiliankolb has modularised this content so it should be immediately possible to do this. 

@maximiliankolb would you've any problem with it moving to Managing Hosts? 

@mdolezelova from talking to Shweta, this seems to fall under her remit of responsibilities? Can we get an opinion on this?

**Comment by mdolezelova** [comment]
> @mdolezelova - this content was originally added by Ian as part of https://issues.redhat.com/browse/SAT-3086
> 
> I'm assuming no real thought went into this as I agree with @maximiliankolb that the content is misplaced.
> 
> Content Management Guide concerns syncing content into Foreman via the Katello plugin, and managing that content in as complex a way as your deployment requires. This is more of a host management exercise.
> 
> I would propose that either it becomes a chapter in the Managing Hosts guide, as essentially it is about host management or it is allowed to stand alone as a guide by itself.
> 
> I would also propose that the "Creating an Activation Key" topic is reused across the guides rather than referenced. I think @maximiliankolb has modularised this content so it should be immediately possible to do this.
> 
> @maximiliankolb would you've any problem with it moving to Managing Hosts?
> 
> @mdolezelova from talking to Shweta, this seems to fall under her remit of responsibilities? Can we get an opinion on this?

@melcorr @maximiliankolb Thank you for looping me in! In general, I think it makes a lot of sense to have smaller and more targeted guides rather than huge guides covering multiple different areas. So I'd be all for for splitting :-) You're right that this falls rather under Shweta's repsonisibilities as Shweta is our content strategist. I will ask Shweta (I'm trying to tag her here, but not sure whether she has a Github account, can't find anything). We would need to know what this split (and thus having a new guide )would require from our side? Do we need to adjust the downstream repo in some way, or will the change happen automatically because of the sync script? But first, we would need to confirm Shweta's ACK for such a change, of course.  So please be patient with us :-)

**Comment by maximiliankolb** [comment]
Rebased to master.

**Comment by ShwetaNaresh** [comment]
@maximiliankolb @melcorr Thank you for highlighting the use case. It is certainly an important use case, and a standalone lean document would help customers get to the required information without much digging. 
Also, I agree that currently the content is incorrectly placed in the Satellite Content Management Guide. It rather needs to be in the Admin Guide if not a standalone guide.

Considering the Satellite 7.0 release epics + bug backlog + whole new team, I would prefer to park this request for now and take it up for Satellite 7.1. We have created a JIRA ticket (https://issues.redhat.com/browse/SATDOC-538) to track this requirement for Satellite 7.1. In the meantime, I am also working with the Satellite product management and engineering team to check if they have any suggestions/thoughts in terms of highlighting this use case for Satellite. 
For now, we will move the content from the Content Management Guide to the Admin Guide. This work is tracked under https://issues.redhat.com/browse/SATDOC-536.

I understand there will be no impact in terms of upstream-downstream content sync because the sources remain the same. The only difference until Satellite creates a separate guide is, Foreman will have a standalone guide for this use case, but for Satellite the content will be available in the Admin guide. Please let me know if my understanding is incorrect.

**Comment by maximiliankolb** [comment]
Hi @ShwetaNaresh 

> @maximiliankolb @melcorr Thank you for highlighting the use case. It is certainly an important use case, and a standalone lean document would help customers get to the required information without much digging. Also, I agree that currently the content is incorrectly placed in the Satellite Content Management Guide. It rather needs to be in the Admin Guide if not a standalone guide.

I completely agree, that's why I've opened this PR.

> Considering the Satellite 7.0 release epics + bug backlog + whole new team, I would prefer to park this request for now and take it up for Satellite 7.1. We have created a JIRA ticket (https://issues.redhat.com/browse/SATDOC-538) to track this requirement for Satellite 7.1. In the meantime, I am also working with the Satellite product management and engineering team to check if they have any suggestions/thoughts in terms of highlighting this use case for Satellite. For now, we will move the content from the Content Management Guide to the Admin Guide. This work is tracked under https://issues.redhat.com/browse/SATDOC-536.

I've opened this PR on October 22nd, so two months ago. To be honest, I am unhappy if it's going to be parked for much longer. It's not like I've opened an issue, but an actual PR with all the work done. 

> I understand there will be no impact in terms of upstream-downstream content sync because the sources remain the same. The only difference until Satellite creates a separate guide is, Foreman will have a standalone guide for this use case, but for Satellite the content will be available in the Admin guide. Please let me know if my understanding is incorrect.

On the Satellite side of things, you would have to change things once you start using Foreman 3.2+. (This PR is against master; and 3.1 has already been branched.)

Would you be up for a meeting to discuss things futher? Feel free to reach out to me.

**Comment by ShwetaNaresh** [comment]
Sure, @maximiliankolb <https://github.com/maximiliankolb>, let's try to
discuss this on January 04 after we are done with the Puppet content
discussion. If we run out of time, I will schedule another meeting for us.
Does that work for you?

Regards

Shweta

**Comment by maximiliankolb** [comment]
> let's try to discuss this on January 04 after we are done with the Puppet content discussion.

Yes, great idea @ShwetaNaresh

**Comment by melcorr** [comment]
@maximiliankolb we can go ahead with this as long as we preserve the build for Satellite as per the Taxonomies guides.

**Comment by maximiliankolb** [comment]
Rebased to master and made content conditional: convert2rhel is visible for Satellite in the content management guide (as was before), and for all other targets in a separate guide.

**Comment by melcorr** [comment]
@maximiliankolb It's my first day back but your PRs are my priority. 
I am sorry that you have waited so long. I will get through testing these this week.

**Review by melcorr — APPROVED** [review]
What is the pixel.png file? I see nothing and can't find it in the test. 

How come this doesn't break the build ? 

It looks good to me. I built and read locally. Thank you. 
Should I merge this and then we add it as a guide in a separate PR?

**Comment by maximiliankolb** [comment]
I've deleted the `pixel.png`. At first, I thought this was necessary because other guides use a "placeholder" image. It seems to work without.

So I think we're good to go.

**Comment by maximiliankolb** [comment]
Rebased to master.

**Comment by melcorr** [comment]
I thought I did this.

**Comment by melcorr** [comment]
Reviewing now.

**Review by melcorr — APPROVED** [review]

**Comment by melcorr** [comment]
Cherry-pick:   4732c079..3a4edc16  3.1 -> 3.1

**Pull request merged**
