### PR TITLE
Rework Deleting Content View Versions module

### PR DESCRIPTION
**Pull request by adamlazik1**
Deleting multiple cv versions is not applicable in 3.1. You can only delete one cv version at a time. Newer versions have the bulk version selection for deletion.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by adamlazik1** [comment]
I don't know whether this also applies to Foreman 3.2. perhaps someone could confirm?

**Comment by adamlazik1** [comment]
For now, it is sufficient if someone reviews this so it can get merged into 3.1.

**Comment by ekohl** [comment]
> I don't know whether this also applies to Foreman 3.2. Perhaps someone could confirm?

3.2 is EOL upstream and there are no downstream consumers of it, so I'm fine with ignoring it.

**Review by maximiliankolb — APPROVED** [review]
LGTM!

**Pull request merged**
