### PR TITLE
Drop GSS proxy privilege separation from direct AD integration proc (3.10)

### PR DESCRIPTION
**Pull request by asteflova**
#### What changes are you introducing?

Applying the changes implemented in https://github.com/theforeman/foreman-documentation/pull/3149 to versions 3.10 and earlier.

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

Explained in https://github.com/theforeman/foreman-documentation/pull/3149

#### Anything else to add? (Considerations, potential downsides, alternative solutions you have explored, etc.)

N/A

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

~~* [ ] Foreman 3.12/Katello 4.14 (Satellite 6.16)~~
~~* [ ] Foreman 3.11/Katello 4.13~~
* [ ] Foreman 3.10/Katello 4.12
* [x] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

### CODE REVIEW

**Comment by asteflova** [comment]
This is just a cherry-pick of changes approved elsewhere (see the description) > `tech review done`.

**Comment by maximiliankolb** [comment]
@asteflova Please use `-x` when cherry-picking commit so that we can see the original commit in the commit message. In which files did you resolve merge conflicts?

**Comment by asteflova** [comment]
Sorry @maximiliankolb poor choice of words in my comment above. This PR doesn't cherry-pick the commit from 3.11 and above because of all the other changes that have been happening in external authentication since 3.11. We are essentially dealing with different documentation sections. What I should have wrote is that I updated the relevant parts of 3.10 docs to match the corresponding parts of 3.11and above. The goal was to remove references to GSS proxy on 3.10 and lower.

Would you prefer me to do a standard cherry-pick? I could do that but then I'd have to apply another commit that would revert some of those changes back to the original state so that the updated sections are consistent with the rest of 3.10 (mostly, this would mean changes to introductions and assembly includes).

**Review by maximiliankolb — APPROVED** [review]
compared to https://github.com/asteflova/foreman-documentation/blob/503934f6e775547484eb0700d5260b69cec6c7a3/guides/common/modules/proc_configuring-the-active-directory-authentication-source-on-projectserver.adoc; LGTM

**Comment by maximiliankolb** [comment]
> Would you prefer me to do a standard cherry-pick?

I was just being lazy and trying to review as little as possible. A cherry-pick "by hand" is also OK here; maybe you can edit your commit message before merging and reference the PR/original commit in some way.

**Comment by asteflova** [comment]
> I was just being lazy

Nah, I was the lazy one and didn't want to deal with all the conflicts and manual reverts. Thanks for the ack.

> maybe you can edit your commit message before merging and reference the PR/original commit in some way.

Will do, thanks for the tip.

**Comment by asteflova** [comment]
Merged to "master" and cherry-picked:

ee9d962b71..884d19b00f  3.9 -> 3.9
8f8e5ea4e5..3519b53092  3.8 -> 3.8
b584901b73..944e3b3106  3.7 -> 3.7
a960379156..ce3466d204  3.6 -> 3.6
e9460ea3aa..ecf8d07442  3.5 -> 3.5

Minor conflicts, for example involving the dropped {package-install-project} attribute.

**Pull request merged**
