### PR TITLE
move linkchecker to an own workflow file

### PR DESCRIPTION
**Pull request by evgeni**
otherwise it prevents previews from being built without a good reason

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* [x] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [x] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
I thought about the same thing. Somehow I thought the linkchecker reused results and it would be complex to reuse it between workflows. Now I see it's actually standalone.

And to expand on this: would it make sense to start marking some builds as required? Perhaps not linkchecker because it's not 100% reliable.

**Comment by evgeni** [comment]
> And to expand on this: would it make sense to start marking some builds as required? Perhaps not linkchecker because it's not 100% reliable.

We could require "build-html"?

**Comment by ekohl** [comment]
@evgeni did you want someone else to cherry pick this?

**Comment by ekohl** [comment]
There are merge conflicts, so I just did 3.8 because I need that now.
   835d6d3b6d69..7234f8d52207  3.8 -> 3.8

**Comment by evgeni** [comment]
Meh, forgot the picks. Will do tomorrow morning

**Comment by evgeni** [comment]
To github.com:theforeman/foreman-documentation.git
   3e7d326db..76f709e51  3.1 -> 3.1
   a08e91fc0..c4f33f7b0  3.2 -> 3.2
   ab77d8ab7..6cfb94d4f  3.3 -> 3.3
   6177957d3..09dde9ba1  3.4 -> 3.4
   8a7b2082f..f534ff77e  3.5 -> 3.5
   eebf2f77b..03e8623bf  3.6 -> 3.6
   463c4f018..d3928e28a  3.7 -> 3.7

The conflicts were only on the `uses: actions/checkout@vX` line where X would differ between 2 3 and 4.

**Pull request merged**
