### PR TITLE
fix performing_a_standard_rhel_installation links

### PR DESCRIPTION
**Pull request by evgeni**
seems they have been renamed on access.redhat.com

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.3/Katello 4.5
* [x] Foreman 3.2/Katello 4.4
* [x] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Comment by evgeni** [comment]
@Lennonka @mdolezelova do you know if there should be a redirect or something on the portal side? seems odd to me to just move the docs and break all incoming links?

**Review by maximiliankolb — APPROVED** [review]
LGTM; merge at your own will once the technicalities are sorted out.

**Comment by mdolezelova** [comment]
> @Lennonka @mdolezelova do you know if there should be a redirect or something on the portal side? seems odd to me to just move the docs and break all incoming links?

Hi @evgeni , thank you for fixing this! Yes, a redirect on the Customer Portal has been requested  by my colleague some time ago.  So any users with the old link bookmarked should be automatically redirected to the current one.

**Comment by evgeni** [comment]
OK, so let's merge this as it's the new link and hope the portal will also redirect at some point :see_no_evil:

**Comment by evgeni** [comment]
8aa32f92..d348bec0  3.1 -> 3.1
   d6222b3f..bcb9c526  3.2 -> 3.2
   414f0520..bbf96b7c  3.3 -> 3.3

**Pull request merged**
