### PR TITLE
Extend procedures for Microsoft Azure

### PR DESCRIPTION
**Pull request by maximiliankolb**
See also https://github.com/theforeman/foreman-documentation/issues/1456

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.3/Katello 4.5
* [x] Foreman 3.2/Katello 4.4
* [x] Foreman 3.1/Katello 4.3

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Can you please review my PR? @AkshayGadhaveRH

You can ignore the second commit; this will be dropped eventually.

**Comment by maximiliankolb** [comment]
Rebased to master which allowed me to drop the second temporary commit. :v:

**Comment by maximiliankolb** [comment]
Ping @AkshayGadhaveRH

**Comment by AkshayGadhaveRH** [comment]
Hey @maximiliankolb, sorry I missed this earlier. I'm on it now.

**Comment by maximiliankolb** [comment]
Rebased to master & friendly reminder :)

**Comment by AkshayGadhaveRH** [comment]
Hey @maximiliankolb, sorry for the delay. This LGTM! :)

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked: ✅ 
   a91f51c9d..aa58f23d8  3.3 -> 3.3
   7810f9f01..5909fc817  3.2 -> 3.2
   1ce580192..b999f4f7d  3.1 -> 3.1

**Pull request merged**
