### PR TITLE
Tweak ifdef not to display a lead-in list for Satellite

### PR DESCRIPTION
**Pull request by asteflova**
[BZ#2223197](https://bugzilla.redhat.com/show_bug.cgi?id=2223197) reports an unnecessary lead-in paragraph.

I updated the ifdef directive not to include satellite, so that the lead-in paragraph doesn't appear in the Satellite version of the guide.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4 on EL8 only)
* [ ] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [ ] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.4 or older.

### CODE REVIEW

**Review by maximiliankolb — APPROVED** [review]
LGTM

**Review by bangelic — COMMENTED** [review]
Agree with Max. LGTM

**Comment by asteflova** [comment]
Thanks both for the review! Is it ready to be merged then?

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked: :heavy_check_mark: 
   800f3b8c9..4308207fa  3.7 -> 3.7
   4117f0ee5..9e0bf3e5b  3.6 -> 3.6
   38ac8bc68..3017f99c5  3.5 -> 3.5

**Pull request merged**
