### PR TITLE
Drop old web content

### LINKED ISSUE #1567: Delete old guides on docs.theforeman.org
We currently do not delete old guides on docs.theforeman.org.

example in the wild: [Foreman Community Forum](https://community.theforeman.org/t/ubuntu-repo-sync-not-working/29950/6?u=maximilian) I suspect there are many more community users that don't actually access the most up to date documentation.

I would kindly ask someone with access to the web server to do a one-time manual cleanup by removing old guides which were left after renaming directories in `guides/`.

I am strongly in favor of broken links instead of old content.

### PR DESCRIPTION
**Pull request by ekohl**
Fixes #1567

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Hi @ekohl 

I am having trouble reviewing this:

* It's a big change, so I couldn't review using Github UI.
* I am currently on MacOS, so I have trouble with changing file names from "Release_notes" to "Release_Notes" ...
* I am missing _how_ you came up with your change.

Running `git diff --name-only c9453c443f25e204f25ae1a0c6d543a9c1cd4274...drop-old-gh-pages-content | wc -l` looks good in terms of number of files changed.

I have continued reviewing using `git diff --name-only c9453c443f25e204f25ae1a0c6d543a9c1cd4274...drop-old-gh-pages-content | cut -f1,2 -d'/' | sort -u` and then checking on each of the five branches is the directories are present (which they should not).

You have deleted files in the following directories that are still present:

3.1:
* 3.1/Administering_with_Ansible
* 3.1/Configuring_Ansible
* 3.1/Configuring_Load_Balancer
...

nightly:
I suspect this directory has been deleted by mistake:
`nightly/Managing_Organizations_and_Locations/`: see  `git:(master) ls guides/doc-Managing_Organizations_and_Locations/`

Would you mind taking another approach (to spare me/anyone else reviewing this): Would it be possible to just remove directories "3.1", "3.2", "3.3", "3.4", and "nightly" and then force a re-deploy by pushing an empty commit to each of those branches?

Thanks for starting this; I was unaware it was a "easy" as deleting files on the "gh-pages" branch!

**Comment by ekohl** [comment]
Rebased to resolve a conflict. I also split this into many commits which should make it easier to review.

**Comment by maximiliankolb** [comment]
This is still hard to review. Would you mind sharing the commands you've used so that I can reproduce your changes? I cannot look at 4k+ files.

**Comment by ekohl** [comment]
Ok, new approach. See each individual commit on how to reproduce it. They essentially all come down to the same thing: remove directory and extract the artifact from GH. Only the last commit is manual, but that's rather easy to review.

**Comment by maximiliankolb** [comment]
Thanks, that's much easier for me to review. I have recreated your PR locally:

```
$ git diff --name-only recreate_pr drop-old-gh-pages-content
3.1/Release_notes/.timestamp-images
3.1/Release_notes/foreman-deb.css
3.1/Release_notes/foreman-el.css
3.1/Release_notes/images/common/1.png
3.1/Release_notes/images/common/1228.png
3.1/Release_notes/images/common/1229.png
3.1/Release_notes/images/common/1230.png
3.1/Release_notes/images/common/2.png
3.1/Release_notes/images/common/3.png
3.1/Release_notes/images/common/4.png
3.1/Release_notes/images/common/5.png
3.1/Release_notes/images/common/6.png
3.1/Release_notes/images/common/7.png
3.1/Release_notes/images/common/PXE-mode.drawio
3.1/Release_notes/images/common/PXE-mode.png
3.1/Release_notes/images/common/PXE-mode.svg
3.1/Release_notes/images/common/PXEless-mode.drawio
3.1/Release_notes/images/common/PXEless-mode.png
3.1/Release_notes/images/common/PXEless-mode.svg
3.1/Release_notes/images/common/compliance_policy_dashboard.png
3.1/Release_notes/images/common/foreman_iss_connected.drawio
3.1/Release_notes/images/common/foreman_iss_connected.png
3.1/Release_notes/images/common/foreman_iss_disconnected_airgapped.drawio
3.1/Release_notes/images/common/foreman_iss_disconnected_airgapped.png
3.1/Release_notes/images/common/foreman_iss_disconnected_non_airgapped.drawio
3.1/Release_notes/images/common/foreman_iss_disconnected_non_airgapped.png
3.1/Release_notes/images/common/notifications1.png
3.1/Release_notes/images/common/orcharhino_provisioning_user_data_sequence.svg
3.1/Release_notes/images/common/orcharhino_pxe_mode.svg
3.1/Release_notes/images/common/orcharhino_pxeless_mode.svg
3.1/Release_notes/images/common/placeholder.png
3.1/Release_notes/images/common/satellite_iss_airgapped.png
3.1/Release_notes/images/common/satellite_iss_disconnected.png
3.1/Release_notes/images/common/user-data-sequence-foreman.drawio
3.1/Release_notes/images/common/user-data-sequence-foreman.svg
3.1/Release_notes/images/common/user-data-sequence-satellite.png
3.1/Release_notes/images/common/user-data-sequence-satellite.txt
3.1/Release_notes/index-foreman-deb.html
3.1/Release_notes/index-foreman-deb.html.log
3.1/Release_notes/index-foreman-el.html
3.1/Release_notes/index-foreman-el.html.log
3.1/Release_notes/index-katello.html
3.1/Release_notes/index-katello.html.log
3.1/Release_notes/index-orcharhino.html
3.1/Release_notes/index-orcharhino.html.log
3.1/Release_notes/index-satellite.html
3.1/Release_notes/index-satellite.html.log
3.1/Release_notes/katello.css
3.1/Release_notes/orcharhino.css
3.1/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/_asciidoc.scssc
3.1/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/_nav.scssc
3.1/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/_site.scssc
3.1/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/default.scssc
3.1/Release_notes/satellite.css
3.2/Release_notes/.timestamp-images
3.2/Release_notes/foreman-deb.css
3.2/Release_notes/foreman-el.css
3.2/Release_notes/images/common/1.png
3.2/Release_notes/images/common/1228.png
3.2/Release_notes/images/common/1229.png
3.2/Release_notes/images/common/1230.png
3.2/Release_notes/images/common/2.png
3.2/Release_notes/images/common/3.png
3.2/Release_notes/images/common/4.png
3.2/Release_notes/images/common/5.png
3.2/Release_notes/images/common/6.png
3.2/Release_notes/images/common/7.png
3.2/Release_notes/images/common/PXE-mode.drawio
3.2/Release_notes/images/common/PXE-mode.png
3.2/Release_notes/images/common/PXE-mode.svg
3.2/Release_notes/images/common/PXEless-mode.drawio
3.2/Release_notes/images/common/PXEless-mode.png
3.2/Release_notes/images/common/PXEless-mode.svg
3.2/Release_notes/images/common/application_life_cycle_orcharhino.svg
3.2/Release_notes/images/common/compliance_policy_dashboard.png
3.2/Release_notes/images/common/foreman_iss_connected.drawio
3.2/Release_notes/images/common/foreman_iss_connected.png
3.2/Release_notes/images/common/foreman_iss_disconnected_airgapped.drawio
3.2/Release_notes/images/common/foreman_iss_disconnected_airgapped.png
3.2/Release_notes/images/common/foreman_iss_disconnected_non_airgapped.drawio
3.2/Release_notes/images/common/foreman_iss_disconnected_non_airgapped.png
3.2/Release_notes/images/common/notifications1.png
3.2/Release_notes/images/common/orcharhino_provisioning_user_data_sequence.svg
3.2/Release_notes/images/common/orcharhino_pxe_mode.svg
3.2/Release_notes/images/common/orcharhino_pxeless_mode.svg
3.2/Release_notes/images/common/satellite_iss_airgapped.png
3.2/Release_notes/images/common/satellite_iss_disconnected.png
3.2/Release_notes/images/common/user-data-sequence-foreman.drawio
3.2/Release_notes/images/common/user-data-sequence-foreman.svg
3.2/Release_notes/images/common/user-data-sequence-satellite.png
3.2/Release_notes/images/common/user-data-sequence-satellite.txt
3.2/Release_notes/index-foreman-deb.html
3.2/Release_notes/index-foreman-deb.html.log
3.2/Release_notes/index-foreman-el.html
3.2/Release_notes/index-foreman-el.html.log
3.2/Release_notes/index-katello.html
3.2/Release_notes/index-katello.html.log
3.2/Release_notes/index-orcharhino.html
3.2/Release_notes/index-orcharhino.html.log
3.2/Release_notes/index-satellite.html
3.2/Release_notes/index-satellite.html.log
3.2/Release_notes/katello.css
3.2/Release_notes/orcharhino.css
3.2/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/_asciidoc.scssc
3.2/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/_nav.scssc
3.2/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/_site.scssc
3.2/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/default.scssc
3.2/Release_notes/satellite.css
3.3/Release_notes/.timestamp-images
3.3/Release_notes/foreman-deb.css
3.3/Release_notes/foreman-el.css
3.3/Release_notes/images/common/1.png
3.3/Release_notes/images/common/1228.png
3.3/Release_notes/images/common/1229.png
3.3/Release_notes/images/common/1230.png
3.3/Release_notes/images/common/2.png
3.3/Release_notes/images/common/3.png
3.3/Release_notes/images/common/4.png
3.3/Release_notes/images/common/5.png
3.3/Release_notes/images/common/6.png
3.3/Release_notes/images/common/7.png
3.3/Release_notes/images/common/PXE-mode.drawio
3.3/Release_notes/images/common/PXE-mode.png
3.3/Release_notes/images/common/PXE-mode.svg
3.3/Release_notes/images/common/PXEless-mode.drawio
3.3/Release_notes/images/common/PXEless-mode.png
3.3/Release_notes/images/common/PXEless-mode.svg
3.3/Release_notes/images/common/application_life_cycle_orcharhino.svg
3.3/Release_notes/images/common/compliance_policy_dashboard.png
3.3/Release_notes/images/common/foreman_iss_connected.drawio
3.3/Release_notes/images/common/foreman_iss_connected.png
3.3/Release_notes/images/common/foreman_iss_disconnected_airgapped.drawio
3.3/Release_notes/images/common/foreman_iss_disconnected_airgapped.png
3.3/Release_notes/images/common/foreman_iss_disconnected_non_airgapped.drawio
3.3/Release_notes/images/common/foreman_iss_disconnected_non_airgapped.png
3.3/Release_notes/images/common/notifications1.png
3.3/Release_notes/images/common/orcharhino_provisioning_user_data_sequence.svg
3.3/Release_notes/images/common/orcharhino_pxe_mode.svg
3.3/Release_notes/images/common/orcharhino_pxeless_mode.svg
3.3/Release_notes/images/common/satellite_iss_airgapped.png
3.3/Release_notes/images/common/satellite_iss_disconnected.png
3.3/Release_notes/images/common/user-data-sequence-foreman.drawio
3.3/Release_notes/images/common/user-data-sequence-foreman.svg
3.3/Release_notes/images/common/user-data-sequence-satellite.png
3.3/Release_notes/images/common/user-data-sequence-satellite.txt
3.3/Release_notes/index-foreman-deb.html
3.3/Release_notes/index-foreman-deb.html.log
3.3/Release_notes/index-foreman-el.html
3.3/Release_notes/index-foreman-el.html.log
3.3/Release_notes/index-katello.html
3.3/Release_notes/index-katello.html.log
3.3/Release_notes/index-orcharhino.html
3.3/Release_notes/index-orcharhino.html.log
3.3/Release_notes/index-satellite.html
3.3/Release_notes/index-satellite.html.log
3.3/Release_notes/katello.css
3.3/Release_notes/orcharhino.css
3.3/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/_asciidoc.scssc
3.3/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/_nav.scssc
3.3/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/_site.scssc
3.3/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/default.scssc
3.3/Release_notes/satellite.css
index_assets/bootstrap-responsive.css
index_assets/bootstrap.css
index_assets/bootstrap.js
index_assets/css.css
index_assets/favicon_180x180.png
index_assets/favicon_32x32.png
index_assets/font-awesome.css
index_assets/foremanhelmet.svg
index_assets/ga.js
index_assets/jquery-ui-1.js
index_assets/jquery.css
index_assets/jquery.js
index_assets/jquery_002.js
index_assets/moment.js
index_assets/scroll.js
index_assets/style.css
index_assets/syntax.css
nightly/Release_notes/.timestamp-images
nightly/Release_notes/foreman-deb.css
nightly/Release_notes/foreman-el.css
nightly/Release_notes/images/common/1.png
nightly/Release_notes/images/common/1228.png
nightly/Release_notes/images/common/1229.png
nightly/Release_notes/images/common/1230.png
nightly/Release_notes/images/common/2.png
nightly/Release_notes/images/common/3.png
nightly/Release_notes/images/common/4.png
nightly/Release_notes/images/common/5.png
nightly/Release_notes/images/common/6.png
nightly/Release_notes/images/common/7.png
nightly/Release_notes/images/common/PXE-mode.drawio
nightly/Release_notes/images/common/PXE-mode.png
nightly/Release_notes/images/common/PXE-mode.svg
nightly/Release_notes/images/common/PXEless-mode.drawio
nightly/Release_notes/images/common/PXEless-mode.png
nightly/Release_notes/images/common/PXEless-mode.svg
nightly/Release_notes/images/common/compliance_policy_dashboard.png
nightly/Release_notes/images/common/foreman_iss_connected.drawio
nightly/Release_notes/images/common/foreman_iss_connected.png
nightly/Release_notes/images/common/foreman_iss_disconnected_airgapped.drawio
nightly/Release_notes/images/common/foreman_iss_disconnected_airgapped.png
nightly/Release_notes/images/common/foreman_iss_disconnected_non_airgapped.drawio
nightly/Release_notes/images/common/foreman_iss_disconnected_non_airgapped.png
nightly/Release_notes/images/common/notifications1.png
nightly/Release_notes/images/common/orcharhino_provisioning_user_data_sequence.svg
nightly/Release_notes/images/common/orcharhino_pxe_mode.svg
nightly/Release_notes/images/common/orcharhino_pxeless_mode.svg
nightly/Release_notes/images/common/satellite_iss_airgapped.png
nightly/Release_notes/images/common/satellite_iss_disconnected.png
nightly/Release_notes/images/common/user-data-sequence-foreman.drawio
nightly/Release_notes/images/common/user-data-sequence-foreman.svg
nightly/Release_notes/images/common/user-data-sequence-satellite.png
nightly/Release_notes/images/common/user-data-sequence-satellite.txt
nightly/Release_notes/index-foreman-deb.html
nightly/Release_notes/index-foreman-deb.html.log
nightly/Release_notes/index-foreman-el.html
nightly/Release_notes/index-foreman-el.html.log
nightly/Release_notes/index-katello.html
nightly/Release_notes/index-katello.html.log
nightly/Release_notes/index-orcharhino.html
nightly/Release_notes/index-orcharhino.html.log
nightly/Release_notes/index-satellite.html
nightly/Release_notes/index-satellite.html.log
nightly/Release_notes/katello.css
nightly/Release_notes/orcharhino.css
nightly/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/_asciidoc.scssc
nightly/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/_nav.scssc
nightly/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/_site.scssc
nightly/Release_notes/sass-cache/eabc6fbbf6bfab1575a0fda2b03180bdcc22267f/default.scssc
nightly/Release_notes/satellite.css
version-2.3/index.html
```

I would consider your first four commits reviewed: 👍 

If the index_assets are no longer is use, then please merge this commit too!

**Comment by ekohl** [comment]
You can verify they're no longer generated by downloading foreman-docs-web-master from https://github.com/theforeman/foreman-documentation/actions/runs/2957998707.

**Comment by maximiliankolb** [comment]
Thanks for taking care of this!

**Pull request merged**
