### PR TITLE
Fixed asciidoc syntax in table entries

### PR DESCRIPTION
**Pull request by mdolezelova**
Cherry-pick into:

* [x] Foreman 3.3
* [x] Foreman 3.2
* [x] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

### CODE REVIEW

**Comment by mdolezelova** [comment]
Hi @melcorr , I had to do this fix because the Administration guide for Satellite 6.11 that I've set up in Pantheon has a build issue. I troubleshooted it downstream to make sure what must be changed in order to make the build work. And with this fix, it works.  Please could you review the PR and merge it if no issues? Thank you!

**Comment by melcorr** [comment]
How on earth is this the cause of the problem? 
Does removing the - signs change the information?

**Comment by melcorr** [comment]
How on earth is this the cause of the problem? 
Does removing the - signs change the information?

**Review by evgeni — CHANGES_REQUESTED** [review]
those settings literally contain `qr-*`, so if you change it here, the rendered doc won't match the reality.
Would using something like:
```
`['lo', 'en*v*', 'usb*', 'vnet*', 'macvtap*', ';vdsmdummy;', 'veth*', 'tap*', 'qbr*', 'qvb*', 'qvo*', 'qr-*', 'qg-*', 'vlinuxbr*', 'vovsbr*', 'br-int']`
```

be an alternative?

**Comment by mdolezelova** [comment]
> those settings literally contain `qr-*`, so if you change it here, the rendered doc won't match the reality. Would using something like:
> 
> ```
> `['lo', 'en*v*', 'usb*', 'vnet*', 'macvtap*', ';vdsmdummy;', 'veth*', 'tap*', 'qbr*', 'qvb*', 'qvo*', 'qr-*', 'qg-*', 'vlinuxbr*', 'vovsbr*', 'br-int']`
> ```
> 
> be an alternative?

I'm sorry, this does not work. I've tried multiple  things, but the only thing I could get it building is removing the dash. The Asciidoc syntax looks correct. Also Asciidoctor itself builds the title correctly. However, the issue is that Pantheon, our publication tool, first translates it to DocBook and then the title is built. And here the translation to Docbook for some reason fails because of the syntax including -*. Honestly, I though this is a mistake as the dash isn't included with the other options. But if it needs to be there, I need to continue to investigate how to make this working.

**Comment by mdolezelova** [comment]
> If you're curious, the data comes from here: https://github.com/theforeman/foreman/blob/75e7c0bf6d3fa1049931ec9000a0819e72201a05/app/registries/foreman/settings/facts.rb#L21-L40

Thank you, @evgeni !

**Comment by mdolezelova** [comment]
This PR is now obsolete. A new one will be created. Closing.

**Pull request closed without merging**
