### PR TITLE
updates Satellite versions in 2.5

### PR DESCRIPTION
**Pull request by ryandeussing**
Updates attributes and docinfo files changing 6.10-beta to 6.10 where appropriate.

### CODE REVIEW

**Comment by ryandeussing** [comment]
@lzap found help with a patch error in a [corner of the internet I've never visited before](https://lukas.zapletalovi.com/2011/11/gits-crying-patch-format-detection.html) ;)

**Comment by maximiliankolb** [comment]
I think this PR is missing https://github.com/theforeman/foreman-documentation/blame/2.5/guides/common/attributes.adoc#L18

**Comment by ryandeussing** [comment]
@maximiliankolb thank you but in this case 6.10 is the value we want in the 2.5 branch, so this PR includes that change.

The advice Ian got, and passed on to me, is that the AccessRedHatComVersion attribute in master should always represent and existing, published version of Red Hat docs. That's why the change to 6.10 didn't get submitted to master first.

If that is poor advice, let me know and I'll spread that information.

**Comment by lzap** [comment]
That is correct, I mean, we don't want to break links in our nightly documentation by referring to documentation set that hasn't been published yet. Nightly is actually our the most visited documentation version as Google prefers it the most. Let me take a look.

**Review by lzap — APPROVED** [review]
LGTM.

**Comment by lzap** [comment]
Merged.

FYI I created a PR for the remaining attribute, we can merge it only after 6.10 docs are out: https://github.com/theforeman/foreman-documentation/pull/838

**Comment by maximiliankolb** [comment]
OK, my bad @ryandeussing

**Pull request merged**
