### PR TITLE
Remove drafts

### PR DESCRIPTION
**Pull request by ekohl**
These have been added, but it doesn't appear to be picked up. Having it in the repository can give false positives when quickly searching for things.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* [ ] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [ ] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

### CODE REVIEW

**Comment by maximiliankolb** [comment]
I am all +1 for this. Do you want to ping both Eric and Maxim who contributed those drafts?

**Comment by ekohl** [comment]
Maxim left the company a while back, so I don't think he's going to finish it.

@ehelms thoughts about the architecture draft? It mostly feels like a copy of https://github.com/theforeman/puppet-pulpcore/#installation-layout. Perhaps we should file it as an issue with a reference to it.

**Comment by ehelms** [comment]
> @ehelms thoughts about the architecture draft? It mostly feels like a copy of https://github.com/theforeman/puppet-pulpcore/#installation-layout. Perhaps we should file it as an issue with a reference to it.

Drop it - if we want to do an architecture document we should just visit it with fresh eyes.

**Comment by ekohl** [comment]
> Assuming this is just "git rm -r drafts": LGTM

It is exactly that.

**Pull request merged**
