### PR TITLE
updates Satellite version to 6.10 in attributes and docinfo files

### PR DESCRIPTION
**Pull request by ryandeussing**
Updates attributes and docinfo files for each upstream title in the Satellite doc set

Cherry-pick into:

* [ ] Foreman 3.0
* [x] Foreman 2.5 (Satellite 6.10)

### CODE REVIEW

**Review by maximiliankolb — COMMENTED** [review]
LGTM. Do you also have to change https://github.com/theforeman/foreman-documentation/blame/master/guides/common/attributes.adoc#L17?

**Comment by lzap** [comment]
Yeah looks like you left one `6.10-beta`, can you change that too? Thanks.

**Comment by lzap** [comment]
FYI it is here:

```
$ ag 6.10-beta
guides/common/attributes.adoc
17::AccessRedHatComVersion: 6.10-beta
```

**Comment by ryandeussing** [comment]
@lzap I can't make this change the fork I based this off of was deleted. You may be able to make this change, otherwise I'll need to make another PR. Apologies.

**Comment by ekohl** [comment]
You can still easily get this change: https://github.com/theforeman/foreman-documentation/pull/796.patch is the URL. With `git am` you can apply it again, including the commit message.

**Review by lzap — APPROVED** [review]
Well, this is not too important for the upstream so I will leave this up to you.

Please file this against 2.5 branch if you want this in 6.10. We are changing the cherry picking policy, from now on we will require PRs for all 2.5 changes to ensure better quality.

**Pull request merged**
