### PR TITLE
Fix URL to download generic bootdisk

### PR DESCRIPTION
**Pull request by maximiliankolb**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6)

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Can you please review my PR? I have tested this on Foreman 3.9 and Foreman 3.5. @stejskalleos

**Review by ares — APPROVED** [review]
Confirmed, I wonder when this changed, but seems like the case for a while

**Comment by ares** [comment]
Thanks @maximiliankolb, merged!

**Comment by maximiliankolb** [comment]
Thanks Marek. Cherry-picks: :heavy_check_mark: 
   8e2fe84db..1c739553f  3.9 -> 3.9
   57e4580f4..2dac1ca3d  3.8 -> 3.8
   e6ac09c10..f37f1ac38  3.7 -> 3.7
   19a1b6783..ec4154db4  3.6 -> 3.6
   b57e6fa81..2d5d188ef  3.5 -> 3.5

**Pull request merged**
