### PR TITLE
Fixed repo ID to reflect that it's Capsule Server

### PR DESCRIPTION
**Pull request by mdolezelova**
Cherry-pick into:

* [x] Foreman 3.2
* [x] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
For upstream, I'd rather not do this. The content of `modules/proc_configuring-repositories-proxy.adoc` is messy and (at least for upstream) `modules/proc_configuring-repositories.adoc` is the correct way.

**Comment by ekohl** [comment]
So the context is that in https://github.com/theforeman/foreman-documentation/commit/bfb5cd8e1ec6105594531bf81058882fee8efaff I changed it because it was clearly wrong for upstream. I missed that it was correct in downstream.

**Comment by evgeni** [comment]
Hmm, and then we ended up "breaking" it again anyways in https://github.com/theforeman/foreman-documentation/commit/3c590ac7b5b1d14a3b746c263553fdf70b167252 :(

**Comment by evgeni** [comment]
Fixed in #1327

**Pull request closed without merging**
