### PR TITLE
Rename Planning Guide in Satellite

### PR DESCRIPTION
**Pull request by Lennonka**
Cherry-pick into:

* [x] Foreman 3.1
* [x] Foreman 3.3

### CODE REVIEW

**Comment by Lennonka** [comment]
@mdolezelova Can you give this an ack? :)

**Comment by maximiliankolb** [comment]
Quick question: are you sure you want to merge this to master and then only cherry-pick to 3.1? Your call, but sounds strange.

**Comment by Lennonka** [comment]
@maximiliankolb I'm not sure, I'm suggesting it because it concerns Satellite only. We can cherrypick to all newer as well if you prefer. LMK

**Comment by Lennonka** [comment]
Note: Cherrypick has to wait until #1230 is cherrypicked.

**Comment by maximiliankolb** [comment]
> @maximiliankolb I'm not sure, I'm suggesting it because it concerns Satellite only. We can cherrypick to all newer as well if you prefer. LMK

@Lennonka I have no preference, but I assume you want it in 3.1 and then 3.5 (will be branched from master), but it would be weird to _not_ want it in 3.3. I would for sure forget about it when 3.5 arrives.

I either recommend either cherry-picking to all versions in between, or open a PR against 3.1 directly if you're unsure about upcoming versions. But totally your call.

**Comment by Lennonka** [comment]
@melcorr Melanie, what's your opinion on the cherrypicks? I think it's not necessary for Foreman higher than 3.1 when it will be included in master.

**Pull request merged**
