### PR TITLE
Consolidate version attribute

### PR DESCRIPTION
**Pull request by maximiliankolb**
See my commit message.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)

### CODE REVIEW

**Comment by maximiliankolb** [comment]
When creating the PR, I thought that I'd use the attribute that aligns nicely with the list of other attributes like "ProjectName" etc: https://github.com/theforeman/foreman-documentation/blob/master/guides/common/attributes-base.adoc#L106

Not sure why I didn't ... :see_no_evil: Anyway, it's fixed now and the diff is still zero.

**Comment by Lennonka** [comment]
> cc @Lennonka This would break our downstream builds, but I think the fix would be simple. We would, however; have to act quickly.

@adamlazik1 Yes, this will definitely break the 6.14 RN build. We have to update the attributes used in the `docinfo.xml` at least. I'm not aware if any of these attributes is used in the individual RNs. I don't know if these attributes are used in any non-upstreamized guides. But we can merge and then fix it. Will you be able to look into it?

**Review by Lennonka — APPROVED** [review]

**Review by Lennonka — COMMENTED** [review]
Damn, it has conflicts with the base branch. Please, rebase.

**Comment by maximiliankolb** [comment]
Rebased to master & resolved the merge conflict :v:

**Comment by adamlazik1** [comment]
> > cc @Lennonka This would break our downstream builds, but I think the fix would be simple. We would, however; have to act quickly.
> 
> @adamlazik1 Yes, this will definitely break the 6.14 RN build. We have to update the attributes used in the `docinfo.xml` at least. I'm not aware if any of these attributes is used in the individual RNs. I don't know if these attributes are used in any non-upstreamized guides. But we can merge and then fix it. Will you be able to look into it?

I would be able to, but we have to agree on a good time to merge this. Ideally, Tuesday or Thursday at noon. I am not sure how long it's gonna take to sync to downstream, but iirc the script runs every hour? Also, it's not just release notes but potentially hammer, api, and, and other downstream guides. Simple sed command should hopefully take care of it.

**Comment by Lennonka** [comment]
@adamlazik1 Yes, the sync runs every hour. I've already created a PR to fix the attribute usage for the RN repo. So I'm leaving it with you to fix the main downstream repo for master and 6.14. Max has the replacement script in the commit message, I think you can use that.

**Review by Lennonka — APPROVED** [review]
Let's do this! :)

**Comment by Lennonka** [comment]
Cherry-picked:
- 31aad3da1..f23edf88a  3.8 -> 3.8
- 98edfe01e..bdc929b4d  3.7 -> 3.7

**Comment by maximiliankolb** [comment]
Thanks Lena and Adam!

**Pull request merged**
