### PR TITLE
Add installer options for setting external database users

### PR DESCRIPTION
**Pull request by wbclark**
* [x] I am familiar with the [contributing](CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.3/Katello 4.5
* [x] Foreman 3.2/Katello 4.4
* [x] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Comment by wbclark** [comment]
cherry picks:

- [ ] Foreman 3.3/Katello 4.5 - https://github.com/theforeman/foreman-documentation/pull/1367
- [ ] Foreman 3.2/Katello 4.4 - https://github.com/theforeman/foreman-documentation/pull/1368
- [ ] Foreman 3.1/Katello 4.3 - https://github.com/theforeman/foreman-documentation/pull/1369

**Comment by maximiliankolb** [comment]
Change looks good to me! Can someone else confirm?

**Review by melcorr — APPROVED** [review]
LGTM!

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked: ✅ 
   cb7445bc..a09c24a2  3.1 -> 3.1
   7f556270..31e25b21  3.2 -> 3.2
   772b39dd..ec2643a8  3.3 -> 3.3

**Comment by maximiliankolb** [comment]
Thanks for the PR! Unless there is a merge conflict, you don't have to open PRs just for cherry-picking from master. :v:

**Pull request merged**
