### PR TITLE
Remove Satellite from anchors

### PR DESCRIPTION
**Pull request by maximiliankolb**
This PR removes `Satellite` from various anchors and fixes the changed xrefs.

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Looks sane, I am confident now that we have the checker. Rebase there are conflicts unfortunately.

If you removed them all, you can actually do a grep-check in the makefile to break build if there is the unwanted word in an id :-) Also you could break the build if there is a dash character or pretty much anything unwanted.

**Comment by maximiliankolb** [comment]
Rebased to master.

I did not yet remove them all, there's still part2 ready for review once this has been merged and I've rebased part2 to master.

**Comment by lzap** [comment]
Merged, thanks. God help us cherry picking stuff. This is gonna hurt.

I briefly tested cherry picking this into 3.0/2.5 and it is not that bad, what we could actually do is to cherry pick this into both branches so that all subsequent commits do apply cleanly. What you think @maximiliankolb and @melcorr ?

**Comment by maximiliankolb** [comment]
> Merged, thanks. God help us cherry picking stuff. This is gonna hurt.
> 
> I briefly tested cherry picking this into 3.0/2.5 and it is not that bad, what we could actually do is to cherry pick this into both branches so that all subsequent commits do apply cleanly. What you think @maximiliankolb and @melcorr ?

Please don't bother cherry-picking this. It's not really critical for other releases IMHO.

**Comment by melcorr** [comment]
No @lzap there have been really massive changes on master. 
@maximiliankolb is a busy boy. 
I hope that the Red Hat team will start to catch up with us.

**Comment by lzap** [comment]
Sure you are right that the train called `master` is long gone and RHD team really needs to work on BZs sooner than later. Let's do part2 then!

**Pull request merged**
