### PR TITLE
Use Ruby 3 in CI

### PR DESCRIPTION
**Pull request by ekohl**
This is to see if 3.1 will build with Ruby 3.

### CODE REVIEW

**Comment by ekohl** [comment]
I've opened https://github.com/theforeman/foreman-documentation/pull/964 to master. Once merged I'll update this to a real cherry pick.

**Comment by lzap** [comment]
If you want full green feel free to pull https://github.com/theforeman/foreman-documentation/pull/966 in.

**Comment by ekohl** [comment]
I'd prefer to merge this now.

**Comment by ekohl** [comment]
It's green now.

**Comment by lzap** [comment]
Thank you!

**Pull request merged**
