### PR TITLE
Highlight difference in shellhook dir vs URL

### PR DESCRIPTION
**Pull request by adamlazik1**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=2173600

Please cherry-pick my commits into:

* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (planned Satellite 6.13)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only)
* [x] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [x] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8, orcharhino 6.2 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.4 or older.

### CODE REVIEW

**Comment by adamlazik1** [comment]
Could someone review this small change?

**Comment by maximiliankolb** [comment]
Is this a case where users read "shellhooks" instead of "shellhook" in the URL?

I am not really a huge fan of adding admonitions everywhere, but I am OK with adding this if you say it's important.

**Comment by adamlazik1** [comment]
Yes. According to our folks from customer support, customers get frustrated because they do not notice the difference in singular vs plural.

**Comment by maximiliankolb** [comment]
> Yes. According to our folks from customer support, customers get frustrated because they do not notice the difference in singular vs plural, which leads to invalid URL.

Then feel free to move ahead.

**Pull request merged**
