### PR TITLE
Bz#1918485 docinfo 6.9beta

### PR DESCRIPTION
**Pull request by suyogsainkar**
Cherrypicked from https://github.com/theforeman/foreman-documentation/pull/381

### CODE REVIEW

**Comment by melcorr** [comment]
Why is there a PR for a cherry pick?

**Comment by lzap** [comment]
We actually tend to review cherry picks too in the code, it gives a better visibility.

But I guess it's not needed given the fact that those SATELLITE branches are not interesting for the Foreman community. Therefore I suggest CP PRs only for Foreman stable branches, e.g. `2.3`.

**Comment by lzap** [comment]
By the way, I suggest you doing fast-forward merging as long as possible. Most of the upstream changes are still valid and you could actually be fast-forwarding until you need a downstream only merge. Once you start cherry picking, the history diverges and you need to keep cherry picking forever.

If you would have fast-fotwarded, you would still have this (still useful) fix: https://github.com/theforeman/foreman-documentation/commit/80b65d711813247a1d0d53291523eba7d48251c8

**Comment by suyogsainkar** [comment]
@melcorr I create my own topic branch from the version branch (SATELLITE-6.9-beta in this case) and perform _git cherry-pick <commit-id>_ This workflow created this new PR when I pushed the cherry-picked commits. @spetrosi clarified this is redundant and I can directly work in the version branch for cherry-picking.

**Pull request merged**
