### PR TITLE
Fix path to postgresql in storage requirement section

### PR DESCRIPTION
**Pull request by mdolezelova**
Cherry-pick into:

* [ ] Foreman 3.2
* [ ] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
This looks OK to me, but it should also be submitted to master and cherry picked to keep it consistent.

**Comment by mdolezelova** [comment]
@ekohl , thank you! Yes, I'm thinking the same. I'm just for the confirmation about the relevance for future version in the BZ. So once it's confirmed, I'll submit a PR against master and request cherry-picking to the later versions. Many thanks!

**Comment by ekohl** [comment]
I can confirm for you that this will be relevant on all versions where EL7 is supported. It will be different on EL8, but EL8 is a massive change that needs to happen throughout the documentation.

**Comment by mdolezelova** [comment]
> I can confirm for you that this will be relevant on all versions where EL7 is supported. It will be different on EL8, but EL8 is a massive change that needs to happen throughout the documentation.

Thank you, @ekohl ! So the corresponding PR for master and future version is https://github.com/theforeman/foreman-documentation/pull/1119.

**Pull request merged**
