### PR TITLE
Fix the EL link that blocked linkchecker to pass

### PR DESCRIPTION
**Pull request by mjivraja**
* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.8/Katello 4.10
* [X] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [X] Foreman 3.6/Katello 4.8
* [X] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [X] Foreman 3.4/Katello 4.6 (EL8 only)
* [X] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* [X] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [X] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

### CODE REVIEW

**Comment by ekohl** [comment]
Duplicate of https://github.com/theforeman/foreman-documentation/pull/2511

**Comment by mjivraja** [comment]
> Duplicate of #2511

Can we go with this PR? As it perfectly redirects to the required chapter.

**Review by ekohl — CHANGES_REQUESTED** [review]
> Can we go with this PR? As it perfectly redirects to the required chapter.

The ID you use in the link doesn't exist for me. I also don't see the benefit in linking to a specific chapter if I read the chrony guide.

**Comment by mjivraja** [comment]
> > Can we go with this PR? As it perfectly redirects to the required chapter.
> 
> The ID you use in the link doesn't exist for me. I also don't see the benefit in linking to a specific chapter if I read the chrony guide.

Closing this one :+1:

**Pull request closed without merging**
