### PR TITLE
cherry-picking some Tuning guide commits to 3.3

### PR DESCRIPTION
**Pull request by jhutar**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Just cherry-picking some Tuning guide commits to 3.3

### CODE REVIEW

**Review by maximiliankolb — APPROVED** [review]
Your changes look reasonable to me. Did you encounter any merge conflicts when cherry-picking?

For future references, please use `git cherry-pick -x SHA1` to add a reference which commit you've cherry-picked to your commit message.

**Comment by jhutar** [comment]
Hello @maximiliankolb . Oh, OK, will use `-x` next time. Thank you.

I only resolved one conflict caused by not fixed typo in one word. I assume I just missed some commit that was fixing that.

What is your recommendation to only see commits relevant to specific guide? I used something like this:

```
git log 3.3..master -- $( grep include doc-Performance_Tuning_Guide/master.adoc | sed 's/.*include::\(.*\.adoc\)\[.*/\1/' )
```

**Comment by maximiliankolb** [comment]
@jhutar Ideally, this would not be necessary because most PRs already request cherry-picks to 3.3, (3.2), and 3.1; so versions used in downstream products.

Your command does not work on my machine. :shrug:

If you want to go the extra mile, compare built guides and then search for commits that contain the changes.

Your PR still looks good to me; so unless there are any objects, I'll merge this.

**Comment by jhutar** [comment]
Thank you Maximilian!

**Pull request merged**
