### PR TITLE
Temporary disable link checker

### PR DESCRIPTION
**Pull request by maximiliankolb**
cc @melcorr 

If this does not work, we should revert the last commit to master. my bad!

### CODE REVIEW

**Review by melcorr — APPROVED** [review]
let's go. 
I'll revert if necessary.

**Comment by maximiliankolb** [comment]
I've missed on item in the Makefile. Give me another chance! ;)

**Comment by melcorr** [comment]
oh damn

**Comment by melcorr** [comment]
@maximiliankolb - do you use IRC at all? I feel we should have some faster way of pinging if necessary.

**Comment by maximiliankolb** [comment]
> @maximiliankolb - do you use IRC at all? I feel we should have some faster way of pinging if necessary.

Maybe I should? It's just so weird that you have to stay connected all the time. I'll think about it. Right now, mail is your best chance. I also use the Github app, so you can literally reach me any time.

**Comment by melcorr** [comment]
> > @maximiliankolb - do you use IRC at all? I feel we should have some faster way of pinging if necessary.
> 
> Maybe I should? It's just so weird that you have to stay connected all the time. I'll think about it. Right now, mail is your best chance. I also use the Github app, so you can literally reach me any time.

I use Matrix and sign into Libera through that. 
It's no problem really - just at times like this it would have been handier!

**Pull request merged**
