### PR TITLE
Add RHEL 9 architectures to provisioning support

### PR DESCRIPTION
**Pull request by adamlazik1**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.5/Katello 4.7 (planned Satellite 6.13)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only)
* [ ] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [ ] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8, orcharhino 6.2 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Comment by adamlazik1** [comment]
@ekohl or @evgeni would you be able to verify this information? The architectures are from https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/considerations_in_adopting_rhel_9/ref_architectures_considerations-in-adopting-rhel-9, however the architectures there are a bit more specific. I am not certain whether to write `x86_64-v2` instead of `x86_64` and `ARMv8.0-A` instead of `ARMv8.0` (or maybe just `ARM`?)

**Comment by evgeni** [comment]
I don't think we support provisioning on anything but x86_64?

cc @ehelms

**Comment by adamlazik1** [comment]
Updated to only include x86_64.

**Review by maximiliankolb — APPROVED** [review]

**Comment by adamlazik1** [comment]
Merged and cherry-picked:
   31bc3bf88..178cc30e0  3.5 -> 3.5

**Comment by Lennonka** [comment]
@evgeni Can you pls confirm that I can cherry-pick this for Sat 6.11+? Because https://bugzilla.redhat.com/show_bug.cgi?id=2192342

**Comment by evgeni** [comment]
6.11+ has full support for rhel9, yes.

**Comment by Lennonka** [comment]
Cherry-picked:
- 84774e38d..4259df097  3.4 -> 3.4
- 1c7984c95..6e9a6aa56  3.3 -> 3.3
- 9c9e5226a..570dd1f4e  3.2 -> 3.2
- a2a25fa72..473c32b5d  3.1 -> 3.1

**Pull request merged**
