### PR TITLE
Added information about truthy and falsy macros

### PR DESCRIPTION
**Pull request by AkshayGadhaveRH**
Added information about the truthy and falsy macros in the Templates Macros section of the Template Writing Reference appendix in the Managing Hosts document.

Cherry-pick into:

* [x] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

@melcorr

### CODE REVIEW

**Comment by melcorr** [comment]
Hey @stejskalleos - this is @AkshayGadhaveRH 's first ever contribution to our docs. Have you any feedback on this for him?

**Review by melcorr — APPROVED** [review]
I built locally and I am happy with the text. 
LGTM. I'll wait a while before merging incase @stejskalleos has some comments.

**Comment by stejskalleos** [comment]
:heavy_check_mark: LGTM!

**Comment by melcorr** [comment]
Cherry-picked to 3.1 as this feature was added with 3.1.1 

   5cbe1d1b..e94f7a4e  3.1 -> 3.1

**Pull request merged**
