### PR TITLE
Use context attribute due to whitespace

### PR DESCRIPTION
**Pull request by maximiliankolb**
See https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Adding_Lifecycle_Environments_content-management

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Looks like an improvement, but given the context is lower case, should `id` also be lower case? But then it's inconsistent with other lines.

**Comment by maximiliankolb** [comment]
@ekohl Yeah, context is lower case. Do you think this use case warrants a new attribute? I am OK either way.

**Comment by adamlazik1** [comment]
I'd say either go full lowercase here or create a new attribute, both is fine for me.

**Comment by maximiliankolb** [comment]
I have added a new attribute for this use case; my PR got slightly bigger. Please re-review @adamlazik1

**Review by adamlazik1 — APPROVED** [review]
LGTM (sorry for the wait I was out of work for a couple of days)

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked: :heavy_check_mark: 
   9dc0451e2..5cb306073  3.8 -> 3.8
   2cd90603b..6700128c7  3.7 -> 3.7

**Pull request merged**
