### PR TITLE
Fixed repo name to reflect that it's a Capsule server

### PR DESCRIPTION
**Pull request by mdolezelova**
Cherry-pick into:

* [ ] Foreman 3.2
* [ ] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

### CODE REVIEW

**Comment by melcorr** [comment]
You're fixing a file name rather than a repo name, right?

**Comment by mdolezelova** [comment]
Hi @melcorr , this is really a confusing case. If you search for the BZ#2056143, it reports that there is a wrong repository name in one section. However, I was already fixing it some time ago in https://github.com/theforeman/foreman-documentation/pull/1095. At that time, I checked the repo ID was fixed correctly, republished the guide and closed the BZ. Yesterday, the BZ was reopened as it was reported that the issue is still there. Not sure how this could happen. I saw there are two similar modules -proc_configuring-repositories.adoc and proc_configuring-repositories-proxy.adoc. So I assumed the first one would be relevant for the Installing Satellite Server guide ans the second one would be relevant for Installing Capsule Server guide. So I though wrong file is included and that's why in this PR I've replaced it with the file relevant for the Capsule (proxy).  However, this still doesn't explain how the change done via https://github.com/theforeman/foreman-documentation/pull/1095 could be reverted. Apologies for the mess, but please do you have any suggestion what to do here?

**Comment by ekohl** [comment]
I think the quickest way now is to keep the current code for upstream, but drop the `satellite` from `ifdef` and make a new block. Then you can also drop the upstream instructions from the proxy document.

**Comment by mdolezelova** [comment]
> I think the quickest way now is to keep the current code for upstream, but drop the `satellite` from `ifdef` and make a new block. Then you can also drop the upstream instructions from the proxy document.

@ekohl , yes, I've created a separate condition for satellite and kept the original file for upstream. Please check my last commit. If it's fine like this, can we merge it, please?
Thank you!

**Review by ekohl — APPROVED** [review]
Thanks!

**Comment by mdolezelova** [comment]
Thank you, @ekohl ! :-)

**Pull request merged**
