### PR TITLE
Fix title URLs Satellite

### PR DESCRIPTION
**Pull request by Lennonka**
* [x] I am familiar with the [contributing](CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [x] Foreman 3.1/Katello 4.3

### CODE REVIEW

**Review by vferschm — APPROVED** [review]
LGTM, all base URLs are correct now

**Comment by Lennonka** [comment]
@melcorr FYI, the deploy / preview is failing here and I don't know why. What am I supposed to do?

**Comment by Lennonka** [comment]
@maximiliankolb So I can merge it, right?

**Comment by maximiliankolb** [comment]
Feel free to merge @Lennonka

**Comment by Lennonka** [comment]
Cherry-picked:
- dfcb83c4..023c4f6f  3.3 -> 3.3
- 5ae3a2cb..56362747  3.1 -> 3.1

**Pull request merged**
