### PR TITLE
Clarify that Template SmartProxy procedure for upgrading Discovery is not always required (branch 3.1)

### PR DESCRIPTION
**Pull request by asteflova**
To follow up on PR https://github.com/theforeman/foreman-documentation/pull/2658, I'd like to introduce the same changes to Foreman 3.1 as well.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

### CODE REVIEW

**Comment by asteflova** [comment]
@adamlazik1 Since you were the one to merge https://github.com/theforeman/foreman-documentation/pull/2658, can you please take a look at this one too?

**Comment by adamlazik1** [comment]
Looks good, but I can't merge since it's marked as draft.

**Comment by asteflova** [comment]
Sorry @adamlazik1 switched to ready for review now.

**Review by Lennonka — APPROVED** [review]
LGTM

**Pull request merged**
