### PR TITLE
Removed reference to Foreman Hooks per SATDOC-918

### PR DESCRIPTION
**Pull request by bangelic**
In Section 3.1 in Before You Begin, I removed any and all references to Foreman Hooks because they have been deprecated for future versions.

Cherry-pick into:

* [x] Foreman 3.3
* [x] Foreman 3.2
* [ ] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

### CODE REVIEW

**Review by melcorr — APPROVED** [review]
Fine by me!

**Review by maximiliankolb — APPROVED** [review]
LGTM!

**Comment by maximiliankolb** [comment]
Merged to master and cherry_picked: ✅ 
   a3360b27..5759c7fa  3.3 -> 3.3
   d397b381..dce2e130  3.2 -> 3.2

Thanks for the PR. Please note that we never use past tense in commit messages. See https://cbea.ms/git-commit/#seven-rules Thanks!

**Comment by bangelic** [comment]
@maximiliankolb Thank you for merging! Can you cherry pick into 3.1 as well? I overlooked it initially and didn't request that but have just requested it now.

**Comment by maximiliankolb** [comment]
@bangelic I have cherry-picked it to 3.1: b5e52c53..cb3a8bee  3.1 -> 3.1

**Pull request merged**
