### PR TITLE
Updated docinfo files for Satellite guides for version 6.12

### PR DESCRIPTION
**Pull request by mdolezelova**
* [ ] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Review by maximiliankolb — APPROVED** [review]
LGTM

**Review by ekohl — APPROVED** [review]

**Comment by mdolezelova** [comment]
Thank you for approving and merging, @ekohl !

**Comment by mdolezelova** [comment]
Hi @ekohl , @maximiliankolb , I was just trying ti set up 6.12 documentation titles in Pantheon (it's RH publication tool) and it still has issues because of the version set in docinfo (it must be set to 6.12). When I've checked the situation, I've found out that the changes in the docinfo.xml files that I've requested in this PR are visible on master, but not on the branch 3.3 (and yes, I've did git pull before checking it). On brach 3.3, the version in docinfo.xml files is still set to to 6.11. Looks like these changes haven't been cherry-picked properly to the branch 3.3 even though it was requested in this PR. Please, could you advise what to do about it or fix it? Thank you!

**Comment by maximiliankolb** [comment]
Cherry-picked to 3.3: ✅ 
   2f8724433..67ffd5592  3.3 -> 3.3

**Comment by mdolezelova** [comment]
Thank you for the cherry-pick, @maximiliankolb ! I confirm that all now works correctly so I can set up documentation titles for Satellite 6.12. Thank you!

**Pull request merged**
