### PR TITLE
Update satellite attributes to RH Satellite version 6.12

### PR DESCRIPTION
**Pull request by mdolezelova**
* [ ] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Unrelated, but in the diff I saw this line:
> +<p>Until <a href="https://bugzilla.redhat.com/show_bug.cgi?id=1788615">BZ#1788615</a> is resolved, this functionality works only on fresh installations of Satellite&#160;6.12 and later.

That BZ is closed as WONTFIX so the text should probably be updated. Should we create a new issue for that or how will we prevent losing track of it?

**Comment by ekohl** [comment]
5da62d84d..2ddb70492  3.3 -> 3.3

**Comment by mdolezelova** [comment]
Hi @ekohl , thank you reviewing and merging! For that reference to a BZ that is now resolved, I'd create a BZ against documentation and assign it to one of our writers, if it's okay? The writer can follow up with the relevant SME and confirm how this should be rephrased. Please, would you agree on this?

**Comment by ekohl** [comment]
Sounds good to me. Will you create the BZ?

**Comment by mdolezelova** [comment]
@ekohl , thanks for the confirmation! Yes, I will, and I will share the link here.

**Comment by mdolezelova** [comment]
@ekohl , here is the BZ link. I've put you on CC.
https://bugzilla.redhat.com/show_bug.cgi?id=2117645
Thanks again for spotting this.

**Comment by ekohl** [comment]
Thanks! I was reading through it and also spotted we point to https://bugzilla.redhat.com/show_bug.cgi?id=1829115 which is closed as resolved. For this I opened https://github.com/theforeman/foreman-documentation/pull/1554. Perhaps we need to go over all of them:
```console
$ rg bugzilla.redhat.com guides
guides/doc-Upgrading_and_Updating/topics/upgrading_content_hosts.adoc
44:. Until https://bugzilla.redhat.com/show_bug.cgi?id=1649764[BZ#1649764] is resolved, from the *Update* list, you must select *via remote execution*.

guides/common/modules/proc_configuring-the-qpid-mgmt-pub-interval-parameter.adoc
27:For more information, see https://bugzilla.redhat.com/show_bug.cgi?id=1335694[BZ 1335694] comment 7.

guides/common/modules/con_postgresql-tuning.adoc
38:For more information, see https://bugzilla.redhat.com/show_bug.cgi?id=1867311#c12[BZ1867311: Upgrade fails when checkpoint_segments postgres parameter configured].

guides/common/modules/proc_configuring-the-cleaning-unused-tasks-feature.adoc
15:Until https://bugzilla.redhat.com/show_bug.cgi?id=1788615[BZ#1788615] is resolved, this functionality works only on fresh installations of {ProjectXY} and later.

guides/common/modules/proc_providing-feedback-on-red-hat-documentation.adoc
19:. Go to the link:https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Satellite[Bugzilla] website.

guides/common/modules/proc_adding-an-amazon-ec2-connection-to-server.adoc
32:Until https://bugzilla.redhat.com/show_bug.cgi?id=1793138[BZ1793138] is resolved, you can download a copy of the SSH keys only immediately after creating the Amazon EC2 compute resource.
```

At least

**Pull request merged**
