### PR TITLE
Bz#1929429 repos attribute sat6.9beta

### PR DESCRIPTION
**Pull request by suyogsainkar**
Cherrypicked from https://github.com/theforeman/foreman-documentation/pull/407

### CODE REVIEW

**Comment by suyogsainkar** [comment]
Closing; contains unintended commits.

**Review by ekohl — COMMENTED** [review]
It looks like you used `git merge`. Typically we use `git cherry-pick -x` to pick commits.

**Comment by melcorr** [comment]
usually we wouldn't cherry-pick from the fork either. 
If you need some help with git, let us know.

**Comment by suyogsainkar** [comment]
@ekohl i used git cherry-pick <commit>
@melcorr I understand. although i prefer working in my own topic branch and create a PR for cherry-picks also (something I've always done), I decided to follow the workflow suggested by you (and Sergei), i.e to commit and push directly from/to a version branch for two of my cherry-picks earlier this week. however, github still showed a notification to create a PR (which I ignored because then it beats the purpose and thought it's just a message and commit(s) have been merged). this obviously caused issues. In my next PR (#399) soon after, those two commits got added automatically along with the new commits.. which were all  merged. but for some reason, git re-added those commits in this PR also - see the first two commits above.
I'll see what's wrong and ping if necessary. thanks.

**Comment by melcorr** [comment]
@suyogsainkar  it sounds to me like your fork is a bit misaligned. I can help you with that. It happened to me before and a few simple setup steps solved it from happening again.

**Pull request closed without merging**
