### PR TITLE
Use installer support for scc-manager plugin

### PR DESCRIPTION
**Pull request by ekohl**
Since Foreman 3.4 there is installer support for scc-manager. This greatly simplifies the steps needed.

This came up in https://github.com/theforeman/foreman-documentation/pull/1773/files#r1018084831.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.5/Katello 4.7
* [x] Foreman 3.4/Katello 4.6
* [ ] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Review by maximiliankolb — APPROVED** [review]
Haven't tested the procedure myself, but LGTM.

**Comment by ekohl** [comment]
Looks like the preview failed here: https://github.com/theforeman/foreman-documentation/actions/runs/3469375923
> Unhandled error: TypeError: Cannot read properties of undefined (reading 'id')

I'll push again to see if it works then.

**Comment by maximiliankolb** [comment]
Seems to work now; feel free to merge!

**Comment by ekohl** [comment]
bd2b61256..121e95676  3.4 -> 3.4
   5c8ae4632..ed020ae23  3.5 -> 3.5

**Pull request merged**
