### PR TITLE
Use guide link instead of xref [fix]

### PR DESCRIPTION
**Pull request by Lennonka**
xref is not working, the target is in another guide.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into: N/A

### CODE REVIEW

**Comment by Lennonka** [comment]
However, the Planning guide is not displayed for some flavors at the moment, so the target will not show. Perhaps we should at least prioritize finishing at least the Glossary. cc @ekohl

**Comment by maximiliankolb** [comment]
https://docs.theforeman.org/nightly/Planning_for_Project/index-foreman-el.html#varl-Glossary_of_Terms-Enterprise_Linux in HTML diff does not work.

**Review by ekohl — APPROVED** [review]
Perhaps we should hide all sections of the planning guide and just show the glossary on platforms where it's not ready?

I don't mind merging this now and doing the planning part later.

**Comment by Lennonka** [comment]
> Perhaps we should hide all sections of the planning guide and just show the glossary on platforms where it's not ready?
> 
> I don't mind merging this now and doing the planning part later.

@ekohl I'm all for this! I'll do that in another PR.

**Pull request merged**
