### PR TITLE
Removed extra period in NOTE number 2

### PR DESCRIPTION
**Pull request by bangelic**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (planned Satellite 6.13)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; planned orcharhino 6.4 on EL8 only)
* [ ] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [ ] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.4 or older.

### CODE REVIEW

**Review by maximiliankolb — COMMENTED** [review]
LGTM; but we could also use `*` to make it an unordered list. Any thoughts?

**Comment by bangelic** [comment]
> LGTM; but we could also use `*` to make it an unordered list. Any thoughts?

Much better as an unordered list. Made the change.

**Review by maximiliankolb — APPROVED** [review]
LGTM!

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked: :heavy_check_mark: 
   ea63d55fb..adcbf7641  3.7 -> 3.7
   6af736327..6eaa41f6f  3.6 -> 3.6
   a6026ebf2..6a542b12e  3.5 -> 3.5

**Pull request merged**
