### PR TITLE
WIP: Deprecation: remove OSTree content support

### PR DESCRIPTION
**Pull request by bbuckingham**
Content management of the OSTree content type was deprecated in a previous release.
This commit is intended to remove all references to the OSTree content type.

Cherry-pick into:

* [x] Foreman 2.5 (Satellite 6.10)
* [ ] Foreman 2.4
* [ ] Foreman 2.3 (Satellite 6.9)
* [ ] Foreman 2.1 (Satellite 6.8)

### CODE REVIEW

**Comment by bbuckingham** [comment]
@ianf77 , FYI.  I wasn't able to assign reviewer on the PR, but wanted to raise to your attention.  Feel free to use or clone this PR in any way that helps.  Thanks!

**Review by melcorr — APPROVED** [review]
Thank you @bbuckingham !

**Comment by ianf77** [comment]
Thank you @bbuckingham !

**Comment by melcorr** [comment]
If there are no further comments or updates to be made @bbuckingham, I'd like to merge this and get it into 2.5

**Comment by bbuckingham** [comment]
@melcorr , I have no additional changes for this one.  I opened as draft/wip based upon initial discussion with @ianf77 .  If the maintainers are good with it, I am as well.

**Pull request merged**
