### PR TITLE
Remove a step where PostgreSQL is stopped and then started

### PR DESCRIPTION
**Pull request by ekohl**
* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.11/Katello 4.13
* [x] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

### CODE REVIEW

**Review by asteflova — APPROVED** [review]

**Comment by apinnick** [comment]
Is this ready to merge and CP?

**Review by maximiliankolb — APPROVED** [review]
@apinnick Yes.

**Comment by asteflova** [comment]
> Is this ready to merge and CP?

I only approved without merging to make sure the PR stayed open for at least [24 hours](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md). It hasn't been 24 _working_ hours yet for me, but it has been for you @apinnick... make of that what you will :smile:

**Comment by apinnick** [comment]
Merged and cherrypicked:

c3ffe2dad0..b358de4480  3.11 -> 3.11
9501fb6418..02d23303af  3.10 -> 3.10

**Pull request merged**
