### PR TITLE
Remove deprecated plugin foreman_hooks

### PR DESCRIPTION
**Pull request by maximiliankolb**
foreman_hooks is deprecated and will be removed with Foreman 3.11. See https://github.com/theforeman/foreman_hooks

This PR is a response to https://github.com/theforeman/foreman-documentation/pull/2950#discussion_r1560682095

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Hey @adamlazik1 Do you know more about the deprecation of the foreman_hooks plugin with Foreman 3.11? Is this official yet? Do you have any BZ? If we decide to drop the docs, we should get at least one ACK from a Foreman developer. Do you know _who_ to ping?

**Comment by adamlazik1** [comment]
All of the webhook and shellhook functionality should remain unchanged as foreman_hooks is being replaced with foreman_webhooks. We actually discussed this today with @adamruzicka so I believe it is safe to keep the documentation.

**Comment by adamlazik1** [comment]
Maybe we could drop the migration procedure, I will confirm that.

**Comment by adamlazik1** [comment]
Okay so we should also keep the migration chapter for people who upgrade from 3.10 and wonder why it suddenly stopped working. We can remove the migration chapter in 3.12. Only things that should be removed in this PR is the mention from glossary and the sentence about backing up foreman hooks.

**Comment by ekohl** [comment]
The removal also deserves a release note. @adamruzicka

**Comment by adamlazik1** [comment]
@ekohl if you are talking about a downstream release note, we have that completed.

**Comment by ekohl** [comment]
@adamlazik1 I was thinking about upstream.

**Comment by adamlazik1** [comment]
@ekohl in that case, should I create a PR to add this RN into upstream manually?

**Review by adamruzicka — APPROVED** [review]
This looks like the right amount of changes

**Review by Lennonka — APPROVED** [review]
LGTM

**Pull request merged**
