### PR TITLE
Turn chronyd module into a short prereq (3.11)

### PR DESCRIPTION
**Pull request by asteflova**
#### What changes are you introducing?

I'd like to drop the chronyd module on branches 3.11 and lower too.

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

Originally, I made this change only on 3.12 and above and thought it would be enough: https://github.com/theforeman/foreman-documentation/pull/3345  Then I came across a [Jira ticket](https://issues.redhat.com/browse/SAT-25004) that pointed out the issue on earlier versions, which made me think that it's probably worth it to apply the fix everywhere after all.

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.12/Katello 4.14 (Satellite 6.16)
* [ ] Foreman 3.11/Katello 4.13
* [x] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

### CODE REVIEW

**Review by maximiliankolb — CHANGES_REQUESTED** [review]
Diff LGTM and URLs work. Please check `guides/common/modules/proc_configuring-a-host-for-registration.adoc` and `guides/common/modules/proc_adding-an-amazon-ec2-connection-to-server.adoc` for xrefs.

**Comment by asteflova** [comment]
> Diff LGTM and URLs work. Please check `guides/common/modules/proc_configuring-a-host-for-registration.adoc` and `guides/common/modules/proc_adding-an-amazon-ec2-connection-to-server.adoc` for xrefs.

That's a good catch. This PR is only for branches 3.10 and lower. The links need to be removed in all branches. Is it okay if we do it in a separate PR? https://github.com/theforeman/foreman-documentation/pull/3419

**Comment by maximiliankolb** [comment]
@asteflova Yes, works for me!

**Comment by asteflova** [comment]
It looks like this PR is only valid for 3.11 and 3.10, due to the link to RHEL 9 docs. I updated the cherry-pick list in the description and will file a new PR (without the RHEL 9 link) for the remaining branches.

**Review by maximiliankolb — APPROVED** [review]
diff LGTM with the follow-up PR https://github.com/theforeman/foreman-documentation/pull/3419

**Comment by asteflova** [comment]
This is just a cherry pick of changes that don't depend on any specific version > `tech review done`.

**Comment by asteflova** [comment]
Merged to 3.11 and cherry-picked:

ef3598154b..9fb73fac8b  3.10 -> 3.10 (conflict, resolved)

**Pull request merged**
