### PR TITLE
Add support for VMware 8 for orcharhino

### PR DESCRIPTION
**Pull request by maximiliankolb**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)

### CODE REVIEW

**Comment by Manisha15** [comment]
Looks good to me.

**Review by ekohl — COMMENTED** [review]
If you didn't patch anything in Foreman to get it to work, can we simply add it for upstream too and drop the "known to work" sentence?

**Review by apinnick — APPROVED** [review]
LGTM

**Review by ekohl — APPROVED** [review]

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked to 3.9: :heavy_check_mark: 
   533f3e1cc..e6032df48  3.9 -> 3.9

**Pull request merged**
