### PR TITLE
Remove trailing whitespaces from files

### PR DESCRIPTION
**Pull request by adamlazik1**
```
find . -type f -iname '*.adoc' | xargs sed -i 's/[ \t]*$//'
```

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* We do not accept PRs for Foreman older than 3.3.

### CODE REVIEW

**Comment by maximiliankolb** [comment]
I think you'd save @apinnick some time rebasing if you re-run your `find | xargs sed` command _after_ we've merged all three PRs to use sentence case in headings.

**Comment by adamlazik1** [comment]
Fair enough, I will wait.

**Comment by adamlazik1** [comment]
Thanks for reminder, rebased.

**Review by maximiliankolb — APPROVED** [review]
diff looks good to me!

**Comment by adamlazik1** [comment]
Merged and cherry-picked:
3.9 .. 3.3 (I broke my cherry-picking script, can't retrieve the message :slightly_frowning_face: )

**Pull request merged**
