### PR TITLE
Correctly render foreman-installer attribute

### PR DESCRIPTION
**Pull request by adamlazik1**
For some weird reason, the missing `+` caused the attribute not to expand. Adding it fixed a formatting issue at the same time. Screenshots from before and after adding `+` below.

BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=2169868

Before:
image

After:
image

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.5/Katello 4.7 (planned Satellite 6.13)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only)
* [x] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [x] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8, orcharhino 6.2 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
The diff suggests you're right. I wonder if we should grep for `{foreman-installer}` in the resulting files to see if there are more, but it's kind of hard to do it in a generic way to find all literal macros.

**Comment by adamlazik1** [comment]
Well, I tried running this monstrosity and was able to find one additional instance of unexpanded attribute:
```
for ATR in $(grep -o :.*: guides/common/attributes* | sort | uniq | cut -d: -f3 | sed -e 's/^/{/' | sed -e 's/$/}/' | grep -Ev '({}|{ https})'); do grep -n $ATR guides/build/*/*.html; done
``` 
I also deleted and rebuilt guides for all five builds prior. That should hopefully be all of them.

**Review by ekohl — COMMENTED** [review]
Thanks!

**Comment by adamlazik1** [comment]
Merged and cherry-picked:
   f06fd7bb0..35ff1b6f8  3.1 -> 3.1
   fbac592c6..32c773a4f  3.2 -> 3.2
   71d48af67..34ac20815  3.3 -> 3.3
   1a41bc444..6b2e5203d  3.4 -> 3.4
   178cc30e0..bd34e2c42  3.5 -> 3.5

* first commit: 3.5 .. 3..1
* second commit: 3.5 .. 3.4

**Comment by maximiliankolb** [comment]
nice catch Adam!

**Pull request merged**
