### PR TITLE
Snippetize a repeating paragraph

### PR DESCRIPTION
**Pull request by Lennonka**
Make a repeating paragraph into a snippet.
No content modification, just code cleanup.
Followup to #2134 

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (planned Satellite 6.13)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only)
* [x] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [x] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8, orcharhino 6.2 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.4 or older.

### CODE REVIEW

**Review by adamlazik1 — APPROVED** [review]
Thanks!

**Comment by Lennonka** [comment]
Cherry-picked:
- b5e91d2c8..6ecc45806  3.6 -> 3.6
- 129a22486..24051dd9d  3.5 -> 3.5
- 68e0564e1..4caa4f98a  3.4 -> 3.4
- 073e556d4..abc31e364  3.3 -> 3.3
- 0b2465794..8dc03ab80  3.2 -> 3.2
- 2120128e5..ed22af012  3.1 -> 3.1

**Comment by maximiliankolb** [comment]
_Snippetize_ is a fantastic word :)

**Comment by Lennonka** [comment]
@maximiliankolb That's the poet in me :))

**Pull request merged**
