### PR TITLE
Reformatted Port Requirement Tables

### PR DESCRIPTION
**Pull request by ianf77**
Organised into satellite incoming and outgoing, capsule incoming and outgoing
PR for 2.5 branch

[doc] Reformat the port requirements tables

https://issues.redhat.com/browse/SAT-3277

Cherry-pick into:

* [ ] Foreman 3.0
* For Foreman 2.5, file a separate PR request

### CODE REVIEW

**Comment by ryandeussing** [comment]
This should just be a cherry-picked changes from #761 and not work from a new branch - if it looks like new work, it will require new full review, which is not the case.

I'll recreate this now.

**Comment by ryandeussing** [comment]
@lzap how right you are. I'm reopening this, I trust Ian has implemented the changes, and there is no time to address the conflicts rebasing is asking of me.

**Comment by lzap** [comment]
@ianf77 fyi if you click on checks here, build-html, Details, Summary there is a foreman-html-docs-BRANCHNAME.zip artifact that can be downloaded. For this PR it is:

https://github.com/theforeman/foreman-documentation/actions/runs/1453565107

After downloading and unpacking the file, you can easily check the content how it was built by our builders.

Snímek obrazovky 2021-11-12 v 16 27 39
Snímek obrazovky 2021-11-12 v 16 28 32
Snímek obrazovky 2021-11-12 v 16 28 42

Now we can compare: https://github.com/theforeman/foreman-documentation/pull/761#issuecomment-965778348

**Comment by lzap** [comment]
Capsule is actually:

Snímek obrazovky 2021-11-12 v 16 31 09
Snímek obrazovky 2021-11-12 v 16 31 21

**Comment by lzap** [comment]
Capsule matches exactly with @ryandeussing screenshot, there was no for the Server but nothing strikes my eyes, LGTM. Thanks!

**Pull request merged**
