### PR TITLE
Add a new global Setting - Allow deleting repos in published CVs

### PR DESCRIPTION
**Pull request by Lennonka**
Cherry-pick into:

* [x] Foreman 3.3
* [x] Foreman 3.2
* [x] Foreman 3.1

### CODE REVIEW

**Comment by Lennonka** [comment]
I'm not sure how the handle community release notes, so I'm adding the following for your consideration:

Enhancement - ISS - CDN config - Network Sync - added validation for the fields:
- Organization label - checks that the organization exists on the upstream server
- same for Lifecycle Env label - checks that it exists in the upstream organization
- same for Content View label - checks that it exists in the upstream organization

Enhancement - removing a content repository (from published CVs)
- now containst a checkbox to doublecheck that you really want to remove it

Enhancement - new Content Setting
- Allow deleting repositories in published content views

**Review by sjha4 — COMMENTED** [review]
LGTM 👍🏼

**Review by melcorr — APPROVED** [review]
LGTM! Thanks

**Comment by Lennonka** [comment]
Mergin' and cherrypickin'

**Comment by Lennonka** [comment]
Cherry-picked:
- 497a05e2..820e9d88  3.3 -> 3.3
- 358b1d99..62b8ab56  3.2 -> 3.2
- 0df66586..22ca8a87  3.1 -> 3.1

**Pull request merged**
