### PR TITLE
don't try to comment the surge link

### PR DESCRIPTION
**Pull request by evgeni**
Turns out, one can't post comments from an action if the PR is opened from a fork, which breaks the workflow :(

* [x] I am familiar with the [contributing](CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Does this mean we still deploy to surge.sh but don't have the bot comment the URL?

**Comment by evgeni** [comment]
That's correct. It deploys, but doesn't comment.

**Comment by evgeni** [comment]
Now at least the overview page of the actions run has a link? https://github.com/theforeman/foreman-documentation/actions/runs/2571126791

better than nothing.

**Review by maximiliankolb — APPROVED** [review]
LGTM!

A assume a lot of colleagues would appreciate it if the preview works for forks as well.

**Comment by evgeni** [comment]
Yeah. I have some ideas how we could bring back the full commenting glory back, but that will need a bit of tinkering and I at least wanted to make it somewhat usable for now.

Thanks for reviewing!

**Pull request merged**
