### PR TITLE
Adding docs for the repository export/import commands

### PR DESCRIPTION
**Pull request by parthaa**
Cherry-pick into:

* [x] Foreman 3.2
* [x] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

### CODE REVIEW

**Comment by melcorr** [comment]
@parthaa - we'll make a writer out of you yet :1st_place_medal: !

**Comment by Lennonka** [comment]
Thanks so much, @parthaa, for kicking this off!
I see several places that could use rewording and small improvements, but it might be more efficient if I take this, fine tune it and submit it in another PR, than suggesting these formal changes in comments. Will either of you mind?

**Comment by parthaa** [comment]
> I see several places that could use rewording and small improvements, but it might be more efficient if I take this, fine tune it and submit it in another PR, than suggesting these formal changes in comments. Will either of you mind?

@Lennonka sounds good to me. Please feel free to fine tune :). I can close this PR

**Comment by Lennonka** [comment]
WIP in #1160
We can close this now.

**Comment by maximiliankolb** [comment]
Closing this PR in favor of https://github.com/theforeman/foreman-documentation/pull/1160.

**Pull request closed without merging**
