### PR TITLE
Allow exporting DEB content

### PR DESCRIPTION
**Pull request by maximiliankolb**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)

### CODE REVIEW

**Review by m-bucher — APPROVED** [review]
Looks good to me.

**Comment by maximiliankolb** [comment]
Can someone please have a look at this? My PR only hides content behind the "if client uses dnf content" which is enabled by default for katello+satellite. In downstream, it depends on the OS of the managed host.

**Review by adamlazik1 — APPROVED** [review]
Looks good stylewise.

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked: :heavy_check_mark: 
   538c863af..f99bef794  3.8 -> 3.8
   27ec52aa2..1df8083d3  3.7 -> 3.7

**Pull request merged**
