### PR TITLE
deploy PR preview to surge.sh

### PR DESCRIPTION
**Pull request by evgeni**
Cherry-pick into:

* [ ] Foreman 3.3
* [ ] Foreman 3.2
* [ ] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

### CODE REVIEW

**Comment by maximiliankolb** [comment]
This is super cool!

Can you please share some insights on what you did to set it up? What did you do on the side of "surge.sh"? Who has credentials for that project?

**Comment by evgeni** [comment]
"nothing". We (@theforeman) have a shared account on surge.sh (I think it was originally created to host documentation for our JavaScript stack. I just took the API token of that account, added it to the secrets of this repo and configured the preview action (see the changed workflow file).

**Comment by maximiliankolb** [comment]
Awesome, sounds good to me. Is there anything that anyone has to know, i.e. do we need to extend the README, contributing guidelines, or PR template? It's pretty obvious from the message from the bot, isn't it?

**Comment by evgeni** [comment]
I think the only not-totally-obvious thing is: it deploys only the version of the docs, the PR is against. like this one is for `master`, so it only deployed `nightly` docs and all other will 404.

So:
* https://theforeman-foreman-documentation-preview-pr-1352.surge.sh/3.3/Installing_Server/index-foreman-el.html is 404
* https://theforeman-foreman-documentation-preview-pr-1352.surge.sh/nightly/Installing_Server/index-foreman-el.html is working

**Comment by maximiliankolb** [comment]
OK, can we append `/release/nightly/` to the URL the bot posts?

**Comment by evgeni** [comment]
No, I don't think we can adjust the message posted. But we could adjust what is deployed?
Right now we deploy both "web" (which is the "cover page with the links") and "html" which is the actual content.

We could deploy only "html" at the root, then there is no ambiguity, but then you'd not notice if we break the cover page (like #1337)

**Comment by maximiliankolb** [comment]
I think the frontpage of the docs needs some love. So I suggest we merge this as is because it's great. I hope, some day in the future, someone will improve the UI/UX.

**Review by maximiliankolb — APPROVED** [review]

**Review by ehelms — APPROVED** [review]
Awesomeness

**Pull request merged**
