### PR TITLE
Cherry-picks for Puppet to 3.8

### PR DESCRIPTION
**Pull request by maximiliankolb**
cherry-picks for https://github.com/theforeman/foreman-documentation/pull/2551

### CODE REVIEW

**Comment by adamlazik1** [comment]
I don't quite understand why changes on guides/common/modules/proc_configuring-repositories-el.adoc are omitted here or why changes on guides/doc-Quickstart/master.adoc are only partial compared to #2551.

**Comment by maximiliankolb** [comment]
I have only cherry-picked what's really required, not cosmetic changes.

**Comment by adamlazik1** [comment]
If there is no harm in then I'd prefer to cherry-pick all of the changes from #2551 to keep as much integrity between master and version branches as possible (i.e. to minimize risk of future merge conflicts)

**Comment by maximiliankolb** [comment]
I have cherry-picked all commits from the PR against master. There were no merge conflicts. @adamlazik1

**Review by adamlazik1 — APPROVED** [review]
LGTM

**Pull request merged**
