### PR TITLE
Add diagram for provisioning method selection

### PR DESCRIPTION
**Pull request by Lennonka**
Will be included in the docs later.

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into: N/A

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
You can do network-based provisioning on VMs as well and that arrow is missing. See https://github.com/theforeman/foreman-documentation/issues/2667 for which compute resources support this.

**Review by maximiliankolb — COMMENTED** [review]
According to downstream docs, you can also do network-based deployments for VMs: https://docs.orcharhino.com/or/docs/sources/guides/almalinux/provisioning_hosts/introduction.html#Provisioning_Methods

**Review by ekohl — COMMENTED** [review]
The arrows to image based and network based overlap, which implies it doesn't matter. Is there a way to get those arrows to separate visually?

**Comment by Lennonka** [comment]
> The arrows to image based and network based overlap, which implies it doesn't matter. Is there a way to get those arrows to separate visually?

@ekohl I can do that, but the message will still be the same. If it matters and the user has to make a decision, then what do they base their decision on?

**Comment by Lennonka** [comment]
Feel free to suggest further improvements in a subsequent PR. Thank you!

**Pull request merged**
