### PR TITLE
Convert to one sentence per line

### PR DESCRIPTION
**Pull request by maximiliankolb**
This PR converts the Configuring Load balancer guide to follow the `one sentence per line` idea.
See #326

### CODE REVIEW

**Review by spetrosi — CHANGES_REQUESTED** [review]
Hi @maximiliankolb, thank you for making this effort. By running grepping the doc-Configuring_Load_Balancer directory for a dot not in the beginning of a line followed by space, I have found two more places where newline is needed:

```
$ grep -rP '(?<!^)\. ' topics/
topics/Promoting_SCAP_Content_to_Clients.adoc:. In the *Default Value* field, enter the FQDN of your load balancer. For example, `_loadbalancer.example.com_`.
topics/Promoting_SCAP_Content_to_Clients.adoc:. Add the puppet module that contains the `foreman_scap_client` puppet class to a Content View. Publish and promote this Content View to your client's environment.

```
Please fix.

**Comment by maximiliankolb** [comment]
Thanks for looking at it @spetrosi 
Fixed it.

**Review by spetrosi — CHANGES_REQUESTED** [review]
I have found that the guide uses the file guides/common/modules/snip_red-hat-images.adoc, we need to apply the one sentence per line format there too.

**Comment by maximiliankolb** [comment]
Fixed and rebased to master.

**Pull request merged**
