### PR TITLE
Added additional information for Capsule upgrade

### PR DESCRIPTION
**Pull request by ianf77**
Upgrade guide for Capsules is missing information

https://issues.redhat.com/browse/SATDOC-509

Cherry-pick into:

* [ ] Foreman 3.0
* For Foreman 2.5, file a separate PR request

### CODE REVIEW

**Comment by ianf77** [comment]
Does this also want to be in master?

**Comment by ekohl** [comment]
I think this is an exception: master has already removed Pulp 2 and this step is really only applicable to 2.5.

**Comment by ianf77** [comment]
That's what I thought.

**Review by ekohl — APPROVED** [review]
I think this is correct. @jlsherrill can you confirm this? Or someone else from the Katello team?

**Comment by maximiliankolb** [comment]
> I think this is an exception: master has already removed Pulp 2 and this step is really only applicable to 2.5.

My bad! You are correct, Pulp2 should no longer be referenced in master. Sorry for the confusion.

**Comment by lzap** [comment]
Please merge @jlsherrill or @jturel ty!

**Review by jlsherrill — APPROVED** [review]

**Pull request merged**
