### PR TITLE
several fixes for rendering of the proxy install guides

### PR DESCRIPTION
**Pull request by evgeni**
See the individual commits for explanations.

Obsoletes: #1208

Cherry-pick into:

* [x] Foreman 3.3
* [x] Foreman 3.2
* [x] Foreman 3.1

### CODE REVIEW

**Comment by evgeni** [comment]
@melcorr @maximiliankolb would one of you have bandwidth to look at this one?

**Review by melcorr — APPROVED** [review]
This all renders well now. 
Does nothing from these scenarios do not apply to Katello at all?

**Comment by evgeni** [comment]
There is no dedicated "katello" proxy guide, so no.

https://docs.theforeman.org/nightly/Installing_Proxy/index-foreman-el.html is actually katello, not foreman, so, uh :woman_shrugging:

**Comment by evgeni** [comment]
To github.com:theforeman/foreman-documentation.git
   4ab85093..1ce69fd1  3.1 -> 3.1
   b2a563b2..685abe8c  3.2 -> 3.2
   cdeb0814..e7a818b2  3.3 -> 3.3

**Pull request merged**
