### PR TITLE
Upsteamize app-host-params chapter

### PR DESCRIPTION
**Pull request by rahulbajaj0509**

### CODE REVIEW

**Comment by rahulbajaj0509** [comment]
One more thing to note in this chapter is, on line number 103, we have `Red Hat Openstack Platform Parameters`. Do we need only OpenStack for the upstream or this is fine?

**Comment by lzap** [comment]
Yes, please introduce variable named OpenStack and for upstream it should be just OpenStack and downstream the full product name Red Hat OpenStack Platform. There do not appear other forms of this product name in this guide so we should be good. Other than that looks good.

**Comment by rahulbajaj0509** [comment]
@lzap I have also arranged the attributes in alphabetical order, this creates no confusion on where to add a new attribute :)

**Comment by lzap** [comment]
No English involved, merging. :-)

**Pull request merged**
