### PR TITLE
Satellite - added RHEL 9 and relevant architectures supported for con…

### PR DESCRIPTION
**Pull request by mdolezelova**
…tent management

* [ ] I am familiar with the [contributing](CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Comment by mdolezelova** [comment]
Hi! This is a necessary update to the "Planning guide" important for downstream. The section is linked from the Release Notes. @Lennonka please can you merge it? Maybe after Vendula (can't find her nick here, sorry) reviews it. So that we speed up the process? Thank you!

**Comment by Lennonka** [comment]
Mergin'

**Comment by melcorr** [comment]
@mdolezelova we need a PR for master for this. It's bad practice to update only the Satellite relevant versions where it is relevant everywhere.

**Comment by Lennonka** [comment]
Cherry-picked:
- d5c585aa..772b39dd  3.3 -> 3.3

**Comment by melcorr** [comment]
yes

**Pull request merged**
