### PR TITLE
Correct index + footer

### PR DESCRIPTION
**Pull request by ekohl**
See the individual commits for details. In short:
* It changes the link order on the index
* It links to latest official docs rather than nightly
* Corrects the source link
* Add a full license text to the repo

### CODE REVIEW

**Review by melcorr — APPROVED** [review]
Thanks @ekohl

**Comment by lzap** [comment]
Right on time, I raised one concern here: https://github.com/theforeman/foreman-documentation/pull/584#discussion_r667666461

We copy a paragraph from Wikipedia, IANAL but we should give them attribution: https://creativecommons.org/use-remix/attribution/

I think the reasonable approach would be to create AUTHORS file programmatically from git history + adding something like "Wikipedia, https://www.wikipedia.org". That would be the bare minimum and I think we could implement it in this PR.

We could go little further and put Wikipedia on the front page of the guide, but for upstream we only generate HTML versions and there is not much there. Which is actually not correct, I think the HTML versions of upstream docs should contain copyright information, perhaps with a link to the AUTHORS file here on github. I think we can do this by modifying `revdate` in `guides/common/header.adoc` or we can use revremark: https://docs.asciidoctor.org/asciidoc/latest/document/revision-information/

**Comment by ekohl** [comment]
Shall I split off the license bit in a separate PR?

**Comment by ekohl** [comment]
So that's https://github.com/theforeman/foreman-documentation/pull/599.

**Review by lzap — APPROVED** [review]
No objections. I can add AUTHORS file.

**Comment by lzap** [comment]
AUTHORS: https://github.com/theforeman/foreman-documentation/pull/601

**Pull request merged**
