### PR TITLE
Run Hammer CLI as non-root user

### PR DESCRIPTION
**Pull request by maximiliankolb**
#### What changes are you introducing?

The dollar sign indicates that you do not need root priviledges to run Hammer CLI commands.

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

the align with our existing convention: `#` for commands that you run as root; `$` for all other commands.

#### Anything else to add? (Considerations, potential downsides, alternative solutions you have explored, etc.)

reproducer:

````
fd -e adoc -t f | xargs sed -i "s/^# hammer /$ hammer /g"
````

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.12/Katello 4.14 (Satellite 6.16)
* [ ] Foreman 3.11/Katello 4.13
* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

### CODE REVIEW

**Comment by apinnick** [comment]
I am SO happy that you are making this change. The `#` prompt has been bothering me for ages!

**Review by apinnick — APPROVED** [review]
LGTM

**Comment by apinnick** [comment]
No CPs?

**Comment by maximiliankolb** [comment]
The only change is/should be "# hammer" -> "$ hammer". Kindly asking for a review @Lennonka

**Pull request merged**
