### PR TITLE
Corrected attribute

### PR DESCRIPTION
**Pull request by ianf77**
Attribute was not rendering correctly

Attribute rendering incorrectly

https://issues.redhat.com/browse/SATDOC-502

Cherry-pick into:

* [ ] Foreman 3.0
* For Foreman 2.5, file a separate PR request

### CODE REVIEW

**Review by maximiliankolb — APPROVED** [review]
LGTM.

**Comment by maximiliankolb** [comment]
@ianf77 Can you please check if this is fine in master branch?

**Comment by ianf77** [comment]
Will do.

**Comment by ianf77** [comment]
Incorrect there too. I'll fix it.

**Pull request merged**
