### PR TITLE
Content filters yum apt

### PR DESCRIPTION
**Pull request by maximiliankolb**
Three small changes; see the each individual commits.

Cherry-pick into:

* [x] Foreman 3.2
* [x] Foreman 3.1

### CODE REVIEW

**Review by lzap — APPROVED** [review]
OK TY

**Comment by lzap** [comment]
Commit(s) 3ebb971f were cherry-picked into: 3.2 3.1
* 823dc750 Add DEB content to content filter overview
* d68ed931 Add DEB content to content filter overview

**Comment by maximiliankolb** [comment]
I cherry-picked the second and third commit to 3.1 and 3.2:

* https://github.com/theforeman/foreman-documentation/commit/77729d9fdbe86f5737fa1feb829aad8e59548e33 & https://github.com/theforeman/foreman-documentation/commit/43b997785e475ba7237eb31777472934a2a7ca1c onto 3.1
* https://github.com/theforeman/foreman-documentation/commit/44a899b03f34b8947f84b9c745ee2a7452d3c976 & https://github.com/theforeman/foreman-documentation/commit/87be2b4b0d1bc060fa8188966d4f0585760a8818 onto 3.2

**Comment by lzap** [comment]
Oh damn, apologies, missed the other two.

**Pull request merged**
