### PR TITLE
Fix 2.5 gha

### PR DESCRIPTION
**Pull request by maximiliankolb**
Trying to figure out why 2.5 does not build & why there was no GHA workflow.

### CODE REVIEW

**Comment by maximiliankolb** [comment]
This PR contains https://github.com/theforeman/foreman-documentation/pull/814 which has been reverted after the GHA workflow failed.

cc @lzap @ianf77

**Comment by lzap** [comment]
This was my fault, this Pulp3 series of changeset was a nightmare. I cherry picked in good faith and it broke:

```
asciidoctor: ERROR: topics/upgrading_satellite_server_parent.adoc: line 34: include file not found: /home/runner/work/foreman-documentation/foreman-documentation/guides/doc-Upgrading_and_Updating/topics/migrating_pulp_content.adoc
```

I propose to request PRs for every single cherry pick from now on so we ensure the tests run fine.

Linkchecker was disabled for 2.5 due to high amount of failures (RHEL docs changed ton of them) in 346d4e9ec4b7f1f251cc4c5360639d5a9f8e3f7b if this is what you ask for.

So 2.5 builds fine now, are we good?

**Comment by maximiliankolb** [comment]
Yeah, I think we're good. At least GHA is green again. 🎉

**Comment by lzap** [comment]
Apologies once again for the mess. From now on, we will require PRs for all backporting work because this way we can ensure tests run fine.

**Pull request merged**
