### PR TITLE
Update available RHEL versions

### PR DESCRIPTION
**Pull request by sabuchan07**
* [ x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ x] Foreman 3.3/Katello 4.5
* [ x] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Please rebase to master.

Also for master, I think we focus entirely on EL8 by now. So you'll probably need two PRs.

**Comment by ekohl** [comment]
> Also for master, I think we focus entirely on EL8 by now. So you'll probably need two PRs.

I wouldn't mind if we first add a change to add EL8, pick that change to all branches and then a commit to remove EL7.

**Review by maximiliankolb — APPROVED** [review]
LGTM with Ewouds comments on EL7 deprecation.

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked: ✅ 
   a21087efe..a0f8240fa  3.3 -> 3.3
   c70c5a00a..079aee45e  3.2 -> 3.2

**Pull request merged**
