### PR TITLE
Refs #26925 - document host register

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Documentation for theforeman/foreman#6813 by no means complete, more as a reminder.
I do not feel like the right person to do this as: I do not understand provisioning, I do not understand how this documentation is being written properly.

Glad to learn though!

Appreciate any help, or even takeovers :)

### CODE REVIEW

**Comment by spetrosi** [comment]
Hi @ezr-ondrej, thank you for rising this PR. Do you know if this feature has been demoed anywhere?
The feature sounds like something that fits better in [3. Registering Hosts](https://access.redhat.com/documentation/en-us/red_hat_satellite/6.7/html/managing_hosts/registering_hosts) in the Managing Hosts guide. The Managing hosts guide is not upstream yet, the work to outsource it is currently in progress.

**Comment by ezr-ondrej** [comment]
Sounds like it :) do we have an estimate? I'd like to have some documentattion for this feature in Foreman 2.2, but it can be in the old manual and we can wait with this PR for the registering hosts guide :-1:

**Comment by lzap** [comment]
Thank you for taking care @ezr-ondrej ! I think one option would be that @spetrosi would simply take this into downstream (gitlab) for now until this is fully on github.

**Comment by spetrosi** [comment]
@lzap, this is not planned for Satellite 6.8 is it?

**Comment by lzap** [comment]
I don't think this is a product feture after reading https://projects.theforeman.org/issues/26925 so no. Sorry to confuse then, this can probably wait here until you guys finish your work.

**Comment by ezr-ondrej** [comment]
> @lzap, this is not planned for Satellite 6.8 is it?

No, this will be foreman 2.22, so it won't make it to Satellite 6.8.

**Comment by spetrosi** [comment]
Hi @ezr-ondrej, I have made some changes to add structure to the topic and use attributes. I also changed the title to make it more descriptive. Please review my changes and tell me if you are satisfied, and if there is enough information in the topic now.

**Comment by spetrosi** [comment]
I opened a BZ to track this work:
https://bugzilla.redhat.com/show_bug.cgi?id=1842470

**Comment by spetrosi** [comment]
Good point about the registration templates @ezr-ondrej. I found out that no such thing is described in our docs yet. What are those registration templates? Are they installed in Foreman by default or users are expected to add them manually? How can users manage them?
Use cases will definitely help, I used some info from the PRs that I've found. Please share any cases that you can think of.

**Comment by ares** [comment]
This functionality is being actively extended, perhaps we should wait until we are done with all the features. Stay tuned

**Comment by lzap** [comment]
I am about to branch off 2.4 series, what is the status please? I can hold off the branching process if this is something that should be in 2.4/4.0. Let me know, thanks.

**Comment by melcorr** [comment]
AFAIK @spetrosi took the content and rewrote it in another PR? Can this close?

**Comment by spetrosi** [comment]
I have done similar work in @359, but @ezr-ondrej will know better if those two PRs are on the same feature

**Comment by lzap** [comment]
Sorry @359 we meant #359. That is a terrible nick by the way, cheers! :-)

**Comment by ares** [comment]
I believe this is no longer relevant, there's already a registration chapter with a lot of details.

**Pull request closed without merging**
