### PR TITLE
Fix LDAP Authentication Source path in ProjectWebUI

### PR DESCRIPTION
**Pull request by mjivraja**
https://bugzilla.redhat.com/show_bug.cgi?id=2176549

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.6/Katello 4.8
* [X] Foreman 3.5/Katello 4.7 (planned Satellite 6.13)
* [X] Foreman 3.4/Katello 4.6 (EL8 only)
* [X] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only)
* [X] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [X] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8, orcharhino 6.2 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.4 or older.

### CODE REVIEW

**Comment by adamlazik1** [comment]
LGTM but does this also apply to 3.1? I do not have a 3.1 instance running right now but I know there were some UI changes in 3.2/3.3?

**Comment by mjivraja** [comment]
> LGTM but does this also apply to 3.1? I do not have a 3.1 instance running right now but I know there were some UI changes in 3.2/3.3?

This applies to even `3.2` and lower. Confirmed on WebUI :+1:

**Review by adamlazik1 — APPROVED** [review]
Thanks for confirming!

**Comment by adamlazik1** [comment]
Merged and cherry-picked:
   743ef505e..95634217c  3.1 -> 3.1
   447d41005..9144d4956  3.2 -> 3.2
   8c0c548a7..402007655  3.3 -> 3.3
   2f2ee0f15..7f3e8304d  3.4 -> 3.4
   fd857b1e9..4e6761f59  3.5 -> 3.5
   98337c0c9..ece030e99  3.6 -> 3.6

**Pull request merged**
