### PR TITLE
Replacing '&' with '&amp;'

### PR DESCRIPTION
**Pull request by apinnick**
#### What changes are you introducing?

Replacing `&` with `&amp;`

#### Why are you introducing these changes? (Explanation, links to references, issues, etc.)

Trying to fix broken XML build in Pantheon

#### Checklists

* [x] I am okay with my commits getting squashed when you merge this PR.
* [ x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.12/Katello 4.14 (Satellite 6.16)
* [ ] Foreman 3.11/Katello 4.13
* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9/6.10)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

### CODE REVIEW

**Review by Lennonka — APPROVED** [review]
LGTM

**Comment by apinnick** [comment]
> I think this breaks the guide in upstream, so a difference in how Pantheon handles it vs plain asciidoc. Any thoughts on rewriting the code avoid needing this in the first place? I'm trying to find the branch where I already did that, but I can't find it now.

@ekohl I am not sure what you mean by "breaks the guide in upstream". The upstream guides all render the code correctly.

`display_info_for_hosts(FOREMAN_API + 'hosts?per_page=1&search=name~' + host_pattern)`

**Comment by apinnick** [comment]
If @ekohl 's [PR](https://github.com/theforeman/foreman-documentation/pull/3406) is merged, we can close this PR.

**Comment by apinnick** [comment]
Merged to 'master' and cherry-picked:
7e4d6f7e78..6c842336eb  3.12 -> 3.12

**Pull request merged**
