### PR TITLE
Modularize managing hosts guide

### PR DESCRIPTION
**Pull request by maximiliankolb**
This PR splits the content of the **Managing Hosts** guide into moduluar items with one heading per file. It also touches anchors, links, and Hammer CLI parameters such as ~Your_Organization~ > `_My_Organization_`.

The built artifacts should be nearly identical.

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Ready for review 🚀 

(This needs to be squashed, obviously.)

**Comment by melcorr** [comment]
Remind me never to go on annual leave again.

**Comment by melcorr** [comment]
If you could rebase this, that would be great.

**Comment by maximiliankolb** [comment]
Rebased to master.

**Comment by melcorr** [comment]
Working on this one now @maximiliankolb 
With any luck, we will finish the modularization PRs today because the rebasing is a pain for sure.

**Review by melcorr — APPROVED** [review]
I didn't find any issues, but I was thinking about how I would manage the cherry-pick because this content is only for 3.2:

https://github.com/theforeman/foreman-documentation/pull/912/

Then I realised this also affected the provisioning, so after I cherry pick, I must go back and remove these bits from 3.1. D'oh.

**Comment by melcorr** [comment]
Cherry-picked to 3.1 
9ac6333

**Pull request merged**
