### PR TITLE
Add EL 9 to supported host OS list

### PR DESCRIPTION
**Pull request by adamlazik1**
Also inverted the order so the newest EL is on top.

[Related BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2144382)

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.5/Katello 4.7
* [x] Foreman 3.4/Katello 4.6
* [x] Foreman 3.3/Katello 4.5
* [x] Foreman 3.2/Katello 4.4
* [x] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Review by evgeni — APPROVED** [review]
Side note: the list of architectures in the next section ("Supported Architectures") is incomplete/wrong (depending on which RHEL version we're talking about), can you track this somewhere that it needs updates?

**Comment by adamlazik1** [comment]
> Side note: the list of architectures in the next section ("Supported Architectures") is incomplete/wrong (depending on which RHEL version we're talking about), can you track this somewhere that it needs updates?

@evgeni  I think it could be a part of this PR if you wish. Would you be able to provide me with information which architectures are supported on which RHEL? Another question, do they differ between Satellite 6.11 and 6.12?

**Comment by evgeni** [comment]
> 



> > Side note: the list of architectures in the next section ("Supported Architectures") is incomplete/wrong (depending on which RHEL version we're talking about), can you track this somewhere that it needs updates?
> 
> @evgeni I think it could be a part of this PR if you wish. Would you be able to provide me with information which architectures are supported on which RHEL? Another question, do they differ between Satellite 6.11 and 6.12?

I don't have that data at hand, so would prefer we get this one in as it does fix actual inconsistencies in the docs, and then find the right data for the other section.

And no, Satellite 6.11 added support for RHEL9 and I am not aware of any changes in the list of supported OSes in 6.12

**Comment by evgeni** [comment]
To github.com:theforeman/foreman-documentation.git
   0376dd7d4..9d99f52d8  3.1 -> 3.1
   149f1ecb0..e0808ecb3  3.2 -> 3.2
   7159f2565..fb6a16ce5  3.3 -> 3.3
   b12f588f4..8631e690f  3.4 -> 3.4
   dec840fd6..6e68f4be6  3.5 -> 3.5

**Pull request merged**
