### PR TITLE
Hide plus sign for orcharhino

### PR DESCRIPTION
**Pull request by maximiliankolb**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)

### CODE REVIEW

**Comment by mjivraja** [comment]
Looks good but except Satellite, the indent and sequencing for all other builds are broken.

**Comment by maximiliankolb** [comment]
I have reworked my MR:

firewall_orcharhino
firewall_satellite
firewall_katello


Does that make sense @mjivraja ?

**Comment by mjivraja** [comment]
> Does that make sense @mjivraja ?

Yes, this is :heart:

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked: :heavy_check_mark: 
   810d971f0..ee1a7f696  3.8 -> 3.8
   d6d3aff09..cb3c00687  3.7 -> 3.7

**Pull request merged**
