### PR TITLE
Remove creating custom SSL certificate section

### PR DESCRIPTION
**Pull request by mjivraja**
Creating a custom SSL certificate for Project Server often created issues for end-users. Hence, we are expecting from end-users to get the custom SSL certificate from the third-party provider within their organization and this section should be removed to avoid confusion.

https://bugzilla.redhat.com/show_bug.cgi?id=2211341

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [X] Foreman 3.6/Katello 4.8
* [X] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [X] Foreman 3.4/Katello 4.6 (EL8 only)
* [X] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4 on EL8 only)
* [X] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [X] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.4 or older.

### CODE REVIEW

**Comment by mjivraja** [comment]
> I would not remove this section. Instead, we should clarify which values need to be adjusted/replaced by users.

@ehelms Can we consider keeping this section and making the procedure accurate?

**Comment by ehelms** [comment]
@maximiliankolb Can you expand on why you think we should keep this as part of our documentation? I don't believe we should be in the business of telling users how to generate certificates. We should support them providing custom certificates, but generating or acquiring custom certificates should be up to the user.

**Comment by maximiliankolb** [comment]
At first I believed this is somewhat Foreman-specific. If it's not, then I think a sufficient alternative would be to a) specify what a user has to create/provide, and b), if possible, add a link on further documentation.

**Review by maximiliankolb — APPROVED** [review]
OK, then I consider this ready. Any other thoughts?

**Review by ehelms — APPROVED** [review]

**Comment by ekohl** [comment]
@ehelms when merging in this repo you should also look at the requested cherry picks. In this case all the way back to 3.1.

**Comment by ehelms** [comment]
> @ehelms when merging in this repo you should also look at the requested cherry picks. In this case all the way back to 3.1.

Do we have this documented somewhere that the merging party is responsible for the cherry picks?
Is Patchback able to help us with this?

**Comment by maximiliankolb** [comment]
@ehelms There's only the "Please cherry-pick my commits into:" in the PR template. So far, we always do this manually. Do you have an example of "patchback" used in Ansible/Pulp?

**Comment by ehelms** [comment]
Here is a Pulp example (note the labels):

 * https://github.com/pulp/pulp_rpm/pull/3200

**Comment by Lennonka** [comment]
@maximiliankolb @ehelms Please, open a new issue for this topic. Discussing topics in merged PRs is a perfect way to make them lost. :)

**Pull request merged**
