### PR TITLE
Modularize provisioning guide

### PR DESCRIPTION
**Pull request by maximiliankolb**
This PR moves some content from assemblies about compute resources to their own files which further modularizes the content.

This PR does not change any content.

Cherry-pick into:

* [x] Foreman 3.1

### CODE REVIEW

**Review by Lennonka — APPROVED** [review]
LGTM. (I can do approvals, yay! :))

**Comment by Lennonka** [comment]
Oh, dear. Please hold it. I'm not sure if we should move assembly heading and intro into a module altogether. See #942 for details.

**Comment by lzap** [comment]
Just a side comment: I am not sure if it is a good practice to cherry pick refactoring (in general), but if you need it for your downstream and you are willing to do the work sure, no problemo :)

**Comment by maximiliankolb** [comment]
> Just a side comment: I am not sure if it is a good practice to cherry pick refactoring (in general), but if you need it for your downstream and you are willing to do the work sure, no problemo :)

Yeah, Melanie and I had the same discussion, but ultimately decided to cherry-pick this (and other refactorings) to 3.1 to make future cherry-picking easier.

**Comment by Lennonka** [comment]
Ok, we've clarified this approach and this one is ready to be merged.

**Comment by maximiliankolb** [comment]
Cherry-pick: https://github.com/theforeman/foreman-documentation/pull/953 ✅

**Pull request merged**
