### PR TITLE
Removed - in line 101 next to self-upgrade

### PR DESCRIPTION
**Pull request by bangelic**
After viewing merged PR #1323, a comment mentioned a command having an extra - so it has been removed. This PR is also needed to cherry pick to 3.3, 3.2, and 3.1 since the original PR didn't get to be cherry picked.

Cherry-pick into:

* [x] Foreman 3.3
* [x] Foreman 3.2
* [x] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

### CODE REVIEW

**Comment by melcorr** [comment]
I had asked you on the PR to indicate where you needed it picked to https://github.com/theforeman/foreman-documentation/pull/1323#issuecomment-1157949104

**Comment by bangelic** [comment]
> I had asked you on the PR to indicate where you needed it picked to [#1323 (comment)](https://github.com/theforeman/foreman-documentation/pull/1323#issuecomment-1157949104)

@melcorr I did see that but put it into this PR with the small change to that merged file. It should be cherry picked to 3.3, 3.2, and 3.1.

**Comment by maximiliankolb** [comment]
Merged to master: ✅ 

*NOT* cherry-picked to 3.1, 3.2, and 3.3 because there's no dash to be removed:

```diff
$ foreman-documentation git:(3.1) git diff head^
diff --git a/guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc b/guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
index e04840b5..91677d83 100644
--- a/guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
+++ b/guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
@@ -94,7 +94,7 @@ ifdef::satellite[]
 +
 [options="nowrap" subs="attributes"]
 ----
-# {package-install} rubygem-foreman_maintain
+# {foreman-maintain} self-upgrade
 ----

 . On {SmartProxyServer}, verify that the `foreman_url` setting points to the {Project} FQDN:
```

Diff after conflict resolution is similar on 3.1, 3.2, and 3.3. `git grep "{foreman-maintain}-" $(git rev-list --all)` did not show any other file or command than the one mentioned above.

**Comment by maximiliankolb** [comment]
> > I had asked you on the PR to indicate where you needed it picked to [#1323 (comment)](https://github.com/theforeman/foreman-documentation/pull/1323#issuecomment-1157949104)
> 
> @melcorr I did see that but put it into this PR with the small change to that merged file. It should be cherry picked to 3.3, 3.2, and 3.1.

@bangelic This was not completely true; I was unable to cherry-pick as mentioned above. Please ping me if you think I missed a cherry-pick.

**Comment by bangelic** [comment]
@maximiliankolb Thanks for the heads up. The original PR #1323 should have been cherry picked and that's on me for not checking it off.

**Comment by maximiliankolb** [comment]
> @maximiliankolb Thanks for the heads up. The original PR #1323 should have been cherry picked and that's on me for not checking it off.

I rather assume that the original PR has _not_ been cherry-picked, because the "fixup" does not need to be cherry-picked.

**Comment by bangelic** [comment]
> > @maximiliankolb Thanks for the heads up. The original PR #1323 should have been cherry picked and that's on me for not checking it off.
> 
> I rather assume that the original PR has _not_ been cherry-picked, because the "fixup" does not need to be cherry-picked.

That was my thought as well but then was asked to submit another PR on my ticket for this to be cherry picked. I defer to your expertise on that.

**Comment by melcorr** [comment]
@maximiliankolb fyi: https://github.com/theforeman/foreman-documentation/pull/1323#issuecomment-1157949104

**Comment by maximiliankolb** [comment]
Sorry Melanie, missed that comment! So the questions goes back to @bangelic

**Comment by bangelic** [comment]
@maximiliankolb I didn't request it in #1323 because I didn't think it was necessary. I was then asked to have it cherry picked in my ticket. I'm not sure if #1323 can be cherry picked but if it can, then it needs to be for 3.3., 3.2, and 3.1. If a new PR needs to be submitted for cherry picking, then that can be done too.

**Comment by maximiliankolb** [comment]
Cherry-picked this fix and the original to 3.1, 3.2, and 3.3: ✅ 
   0b0151b4..a7ff0ad2  3.1 -> 3.1
   2b7af14b..a4564f06  3.2 -> 3.2
   3f05cde9..e759eb4e  3.3 -> 3.3


For future reference, it's generally the responsibility of the creator of the PR to ensure it gets reviewed, merged, and then cherry-picked. But no worries, we've fixed it now.

**Pull request merged**
