### PR TITLE
s/Infoblox_hostname/infoblox_hostname

### PR DESCRIPTION
**Pull request by melcorr**
As part of Issue #32

### CODE REVIEW

**Comment by melcorr** [comment]
@lzap From what I can tell, your link checker can't handle the example links we add to the docs?

**Comment by lzap** [comment]
Yes, this will not work. I suggest to drop this practice completely, in tech we like to use fully qualified domains anyways and the best practice IMHO is to use "infoblox.example.com".

http://www.example.com : Example Domain

_This domain is established to be used for illustrative examples in documents. You may use this domain in examples without prior coordination or asking for permission._

However, this was not the reason why Travis failed. If you open it up, you will see this: Error: ReadTimeout: HTTPConnectionPool(host='ipxe.org', port=80): Read timed out. (read timeout=60) 

This means that the http://ipxe.org links could not be verified because the remote host did not respond. This will happen from time to time, just rebase and force push to trigger tests again to retest. I just tested this in a train from Wien to Munich and I saw zero errors :-)

**Comment by melcorr** [comment]
Done!

**Comment by lzap** [comment]
Nice it looks like it ignored the underscores. Great.

**Pull request merged**
