### PR TITLE
Isolated topology diagram: Remove 5000 between capsule and server

### PR DESCRIPTION
**Pull request by asteflova**
In https://github.com/theforeman/foreman-documentation/pull/2491, I missed port 5000 connecting isolated capsule and server. This PR removes that connection.

EDIT: During review, more issues with the diagram have come up, so additional commits in this PR have updated other parts of the diagram. Namely:

* TCP 443 now connects Pulp on capsule and Pulp on server
* Pulp and Candlepin no longer talk to Qpid
* Pulp and Pupper Server on the capsule side have been swapped

FYI, I will follow this PR up with another PR for 3.2 and 3.1, and also for downstream Satellite 6.10.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* [ ] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [ ] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* We do not accept PRs for Foreman older than 3.1.

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
I can confirm that since Pulp 3 this is gone. There's another mistake though: Pulp on Isolated Capsule connects to TCP 443 to Pulp, not Foreman.

Another is that Pulp and Candlepin no longer talk to Qpid. Not even internally. Until Foreman 3.8 it's only Foreman that talks to Qpid (on Satellite server). After that Qpid is dropped altogether.

**Comment by asteflova** [comment]
> There's another mistake though: Pulp on Isolated Capsule connects to TCP 443 to Pulp, not Foreman.

https://github.com/theforeman/foreman-documentation/pull/2500/commits/dfc9f527d3030feec3557c3ffa521f23c962e31b redirects the TCP 443 arrow (originating from pulp on capsule) from Foreman to Pulp on the server.
 
> Another is that Pulp and Candlepin no longer talk to Qpid. Not even internally.

https://github.com/theforeman/foreman-documentation/pull/2500/commits/e3f62b2a62c788b3eb7bdc54384747fb2d63ab62 then removes two Qpid connections: to Candlepin and Pulp on the server.

> Until Foreman 3.8 it's only Foreman that talks to Qpid (on Satellite server).

I think the diagram covers this with the arrow between Qpid and Qpid on internal capsule, is that right? Or is there some more editing required to cover this?

> After that Qpid is dropped altogether.

So the diagram will need editing for 3.9 to remove Qpid?

**Comment by asteflova** [comment]
> > So the diagram will need editing for 3.9 to remove Qpid?
> 
> Foreman 3.8 drops it, but that also implies 3.9 yes.

Ok, I will do that in another PR for 3.8+.

> 
> Does it make sense to swap Pulp and Puppetserver on the Isolated Capsule so you don't have lines crossing each other?

A good idea, https://github.com/theforeman/foreman-documentation/pull/2500/commits/f06885d94b3d312fa510f256483294e2a76e45cd.

**Comment by ekohl** [comment]
> Ok, I will do that in another PR for 3.8+.

FYI, @bangelic has it on his agenda to work on katello-agent removal.

> A good idea, [f06885d](https://github.com/theforeman/foreman-documentation/commit/f06885d94b3d312fa510f256483294e2a76e45cd).

Much nicer. Thanks

@evgeni @ehelms mind taking a look as well?

**Comment by asteflova** [comment]
I believe that's all that is needed for this PR so I'm marking it as ready for review.

There will be more PRs needed:
1. Removing Qpid for 3.8+
2. Making the same changes that have been done in this PR for 3.1. and 3.2. upstream. (these releases use a different style for graphics)
3. Updating 6.10 downstream with the diagram from 2.

I will submit these PRs after this one is merged.

**Comment by asteflova** [comment]
> FYI, @bangelic has it on his agenda to work on katello-agent removal.

@bangelic I don't want to step on your toes here :) so I will not continue editing the diagram to remove Qpid for 3.8+. I guess removing something this big would require help from the design team anyway... But let me know if you think I can help.

**Comment by evgeni** [comment]
A little scope creep (this PR talks about removing port 5000, which it correctly does):
I think these days Katello talks to Pulp on the external capsule on port 443 to instruct it to perform syncs etc, vs in the past it has been Pulp-to-Pulp communication when it came to syncing external capsules.
That said, it's a technical detail which doesn't really matter network wise (it's just a different process on the same machine initiating the connection), and I am not even 100% sure I am correct.

So take this comment as an ACK for the change at hand and probably a TODO "verify external-capsule pulp communication further"? :)

**Comment by ehelms** [comment]
Overall notes, can address them in PRs and updates as you like:

- Qpid and Qpid Dispatch Router gone
- Foreman talks to the Foreman Proxy on the server
- We should include PostgreSQL and Redis
- I'd move Pulp out of the "Internal Capsule" box and put it alongside Foreman and Candlepin
- Apache is integral part of the architecture and I think it's instructive to include it so folks understand how the communication routes through it for services
- We can drop the term "Isolated Capsule" in favor of "Capsule"
- Same for a host - lets just say Host
- We should add templates and registration to the Foreman Proxy
- Drop '8443' for RHSM

**Comment by asteflova** [comment]
Thanks for all the comments. I have recorded the feedback in a separate ticket that I have to review the whole Architecture guide; will work on it then, probably within the next couple of months.

As of now, I believe the diagram can be merged as-is. It's not perfect, but at least some of the issues have been corrected, and there is a plan for further improvements.

**Comment by asteflova** [comment]
@ekohl I think it would be better _not_ to squash when it comes to diagrams.

**Comment by asteflova** [comment]
I don't think a diagram change needs a style review... so I'll boldly label this as 'style review done'. Merge reviewers, feel free to tell me otherwise.

**Comment by asteflova** [comment]
@Lennonka You merged the previous PR related to this diagram, can you please take a look at this one as well? TL;DR even more things were wrong with it.

**Comment by Lennonka** [comment]
@asteflova I don't see why not to squash the commits. It's a binary format, it's not like you can revert just a piece of the image. Why do you think it's a bad idea to squash them?

**Comment by asteflova** [comment]
@Lennonka If there is a need to revert some changes in the diagram, being able to bring up a partially modified version would make it easier. But I guess it's silly, that's probably not going to be needed anyway. So go ahead and squash.

**Comment by Lennonka** [comment]
Cherry-picked:
- 39ce2ebc6..0878a6e05  3.8 -> 3.8
- cd1ab293e..44d0ffee0  3.7 -> 3.7
- 0f04dcb86..4058fa841  3.6 -> 3.6
- 672bf3cb9..18386af1d  3.5 -> 3.5
- e575e2e1f..3172cedb3  3.4 -> 3.4
- 6ac675985..681d71d77  3.3 -> 3.3

**Pull request merged**
