### PR TITLE
Specify adding individual Proxmox nodes

### PR DESCRIPTION
**Pull request by maximiliankolb**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [x] Foreman 3.8/Katello 4.10
* [x] Foreman 3.7/Katello 4.9 (Satellite 6.14)

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Does this wording make sense to you? @Manisha15

**Comment by mjivraja** [comment]
`Promox Server` is also mentioned in `proc_creating-hosts-on-proxmox.adoc`. Are they impacted?

**Comment by maximiliankolb** [comment]
> `Promox Server` is also mentioned in `proc_creating-hosts-on-proxmox.adoc`. Are they impacted?

Yes, good catch. Changed!

cc @mjivraja @Manisha15

**Comment by Manisha15** [comment]
> > `Promox Server` is also mentioned in `proc_creating-hosts-on-proxmox.adoc`. Are they impacted?
> 
> Yes, good catch. Changed!
> 
> cc @mjivraja @Manisha15

Looks good.

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked: :heavy_check_mark: 
   1471ee261..9b8054606  3.9 -> 3.9
   d00a4ed9a..409bc2dcf  3.8 -> 3.8
   0f753920c..42d744abe  3.7 -> 3.7

**Pull request merged**
