### PR TITLE
Additional arguments in foreman-maintain

### PR DESCRIPTION
**Pull request by mjivraja**
The additional arguments that can be used for foreman-maintain can be listed while updating server to next minor version.

https://bugzilla.redhat.com/show_bug.cgi?id=2189967

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [X] Foreman 3.6/Katello 4.8
* [X] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [X] Foreman 3.4/Katello 4.6 (EL8 only)
* [X] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4 on EL8 only)
* [X] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [X] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.4 or older.

### CODE REVIEW

**Comment by mjivraja** [comment]
The merged changes of this PR shall be applicable to this PR #2233 as well.

**Comment by adamlazik1** [comment]
Should it be explained what whitelist does and what whitelist arguments can be?

**Comment by mjivraja** [comment]
> Should it be explained what whitelist does and what whitelist arguments can be?

IMO, users may be aware of. But, let's wait for other reviews.

**Review by maximiliankolb — COMMENTED** [review]
I am against recommending users to bypass certain upgrade checks; it is potentially dangerous if users just reword "check" to "run" to perform the upgrade.

But we're currently not using the procedure in downstream. If someone ACKs this, then it's good to go.

**Comment by ekohl** [comment]
Like the others I doubt this is a good direction. A few reasons:

* whitelist is poorly named: it's really a blacklist where it doesn't run checks that were listed (https://github.com/theforeman/foreman_maintain/pull/723 renames it to `--skip`)
* We don't want users to skip checks.
* We don't provide any help on how to find out which checks the user could list

So overall I'd say this is not a direction we should head into. At best you could add a section on how to skip certain checks but it should not be the default user instruction.

**Comment by mjivraja** [comment]
> Like the others I doubt this is a good direction. A few reasons:
> 
> * whitelist is poorly named: it's really a blacklist where it doesn't run checks that were listed ([Change --whitelist to --skip foreman_maintain#723](https://github.com/theforeman/foreman_maintain/pull/723) renames it to `--skip`)
> * We don't want users to skip checks.
> * We don't provide any help on how to find out which checks the user could list
> 
> So overall I'd say this is not a direction we should head into. At best you could add a section on how to skip certain checks but it should not be the default user instruction.

Agree with this. Even prior collaborations with SMEs had the same point to direct the users in other ways, instead of whitelisting the parameters.

As it is not recommended to add the argument to this, I am closing this PR. Adding a note on my side of having some resources for users on using arguments.

**Pull request closed without merging**
