### PR TITLE
Rename check box to checkbox

### PR DESCRIPTION
**Pull request by maximiliankolb**
find . -type f -iname "*.adoc" | xargs sed -i "" "s/check box/checkbox/g"

See also https://github.com/theforeman/foreman-documentation/pull/1464#discussion_r931045223

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.3/Katello 4.5
* [x] Foreman 3.2/Katello 4.4
* [x] Foreman 3.1/Katello 4.3

Maybe it's easier to run the command instead of cherry-picking.

### CODE REVIEW

**Comment by Lennonka** [comment]
Awesome, thanks!
LGTM, merging

**Comment by maximiliankolb** [comment]
Reran the command. @Lennonka

**Comment by Lennonka** [comment]
LGTM, merging

**Comment by Lennonka** [comment]
Please, file separate PRs for all three cherry-picks, there are conflicts on all of them.

**Pull request merged**
