### PR TITLE
Fix missing images directories

### PR DESCRIPTION
**Pull request by lzap**
SSIA

Ask for rebase before merging please, bigger changes of the Makefile and GHA can cause issues.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
My bad. I'll update the cherry picks too.

**Comment by lzap** [comment]
No problem you could not see this and it was green. We need to ask to rebase only on those PRs which add new guide directories or delete old ones.

**Comment by ekohl** [comment]
Normally it's not as big a deal, but we recently had many big, structural changes in flight. I should have been aware of that.

**Comment by ekohl** [comment]
I think this was only needed in 3.1 since you didn't pick the images restructure to 3.0 and older, right?

**Pull request merged**
