### PR TITLE
Remove a paragraph about SSSD

### PR DESCRIPTION
**Pull request by fiyyyu**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.5/Katello 4.7 (planned Satellite 6.13)
* [x] Foreman 3.4/Katello 4.6 (EL8 only)
* [x] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only)
* [x] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [x] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8, orcharhino 6.1 on EL7, orcharhino 6.2 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Comment by adamruzicka** [comment]
We probably don't have anyone who really knows this area. What is the motivation behind dropping this sections?

**Comment by fiyyyu** [comment]
> We probably don't have anyone who really knows this area. What is the motivation behind dropping this sections?

@adamruzicka I have pinged you in a BZ comment, you can see the context there.

**Review by adamruzicka — APPROVED** [review]
I see, that makes sense. Very well then, let's get rid of it

**Comment by adamlazik1** [comment]
Merged and cherry-picked:
   ccf03f947..72e33553c  3.2 -> 3.2
   0c0626994..c2d5bcfe9  3.3 -> 3.3
   39c72206c..3b2d4081b  3.4 -> 3.4
   3f1cccbe0..3af9ab914  3.5 -> 3.5

Could not cherry-pick to 3.1 because of merge conflict. Please create a new PR against 3.1 if you wish to apply changes there as well.

**Pull request merged**
