### PR TITLE
Change capitalization of guide titles

### PR DESCRIPTION
**Pull request by apinnick**
- Change guide title capitalization from title case to sentence case

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.10/Katello 4.12
* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* We do not accept PRs for Foreman older than 3.3.

### CODE REVIEW

**Review by maximiliankolb — APPROVED** [review]
diff LGTM. Any other comments? Else I'll merge as is.

**Comment by apinnick** [comment]
@maximiliankolb I just noticed that the docinfo.xml files are not using the attributes. So I need to fix those as well.

**Comment by apinnick** [comment]
@maximiliankolb I was mistaken. All the docinfo.xml files have the doc title attributes, so they are fine. Only change I made was a level offset fix to an 'include'. Please review.

**Review by maximiliankolb — APPROVED** [review]
LGTM. I assume you have tested the URLs for Satellite docs? Ping me and I will merge + cherry-pick both commits.

**Comment by apinnick** [comment]
> LGTM. I assume you have tested the URLs for Satellite docs? Ping me and I will merge + cherry-pick both commits.

@maximiliankolb  I can't test the URLs before this PR is merged because they have to be configured in Pantheon. When this PR is merged and synced with downstream, then I will update the titles in Pantheon so that the new URLs work.

**Comment by maximiliankolb** [comment]
Merged to "master" and cherry-picked:
   358a1440d0..7b553e718a  3.10 -> 3.10
   e02e4b1d16..997ca5ae91  3.9 -> 3.9

**Pull request merged**
