### PR TITLE
Fix URL in Configuring Load Balancer module

### PR DESCRIPTION
**Pull request by adamlazik1**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.4/Katello 4.6
* [x] Foreman 3.3/Katello 4.5
* [x] Foreman 3.2/Katello 4.4
* [x] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
I should have finished https://github.com/theforeman/foreman-documentation/pull/1750, because I also found it there. I think there are also broken links in https://github.com/theforeman/foreman-documentation/pull/1750/files#diff-e1b7c7c06931cd1f3fd88647a41a14855dd3789d7574f502325509d6ce91ccbf and https://github.com/theforeman/foreman-documentation/pull/1750/files#diff-f02b6bd39a5cdffa51e59f4064120726c7245630b9aa8ea3b566225f3842d943 though I'm not sure. Still, using more macros was better.

I'd also be happy if you (or anyone else) take over https://github.com/theforeman/foreman-documentation/pull/1750.

**Comment by adamlazik1** [comment]
> I think there are also broken links in https://github.com/theforeman/foreman-documentation/pull/1750/files#diff-e1b7c7c06931cd1f3fd88647a41a14855dd3789d7574f502325509d6ce91ccbf and https://github.com/theforeman/foreman-documentation/pull/1750/files#diff-f02b6bd39a5cdffa51e59f4064120726c7245630b9aa8ea3b566225f3842d943 though I'm not sure.

Confirmed. I will address this in #1775 since it already deals with the Disconnected guide links.

**Comment by adamlazik1** [comment]
Merging this since I verified the link works and I see no other comments concerning this specific link.

**Comment by adamlazik1** [comment]
Merged and cherry-picked:
057933c42..7542b9355  3.1 -> 3.1
38c5b8ddb..ed66bf799  3.2 -> 3.2
b6fb61a4e..d0c4106dd  3.3 -> 3.3
397c0d0e4..41e6c73e6  3.4 -> 3.4
bc38e724b..a9ac79877  3.5 -> 3.5

**Pull request merged**
