### PR TITLE
Fix the ProductVersion attribute

### PR DESCRIPTION
**Pull request by mdolezelova**
Cherry-pick into:

* [ ] Foreman 3.2
* [ ] Foreman 3.1
* For Foreman 3.0 or older, file a separate PR request

### CODE REVIEW

**Comment by lzap** [comment]
Can you rebase and push again? This will trigger tests again. Github Actions had an outage yesterday: https://www.githubstatus.com/history

**Comment by mdolezelova** [comment]
Hi @lzap , thank you for the review and the info! I'm not familiar with the process, apologies. Please could you give me a clue? I've created this topic branch from the branch 2.5. So to do the rebase that you're suggesting - on which branch I need to be in my forked repo and which command I need to execute? Thank you and apologies!

**Comment by ekohl** [comment]
@lzap looks like CI did run here. Is there a problem with the results?

**Comment by lzap** [comment]
I only see 2 runs out of 5. But assuming that both ccutil and html was built, it should be fine.

**Comment by mdolezelova** [comment]
Thank you for merging, @lzap !

**Pull request merged**
