### PR TITLE
Add EL8 KVM guest image links

### PR DESCRIPTION
**Pull request by mjivraja**
There is a need to remove KVM guest image links of EL6 for project version 3.2 and below where these OS versions are no longer supported. Therefore, we have added the link of EL8 in place of EL6.

https://bugzilla.redhat.com/show_bug.cgi?id=2133957

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.5/Katello 4.7
* [ ] Foreman 3.4/Katello 4.6
* [ ] Foreman 3.3/Katello 4.5
* [X] Foreman 3.2/Katello 4.4
* [X] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Comment by mjivraja** [comment]
This PR is referring to #1777

**Comment by ekohl** [comment]
Build failure looks unrelated. I've opened https://github.com/theforeman/foreman-documentation/pull/1804 to see if that fixes it.

**Comment by mjivraja** [comment]
> Build failure looks unrelated. I've opened #1804 to see if that fixes it.

Thanks @ekohl :heart:

**Comment by adamlazik1** [comment]
FYI, there are still these two modules included
```
include::modules/proc_completing-the-rhel7-image.adoc[leveloffset=+1]
include::modules/proc_completing-the-rhel6-image.adoc[leveloffset=+1]
```
which look related to the two modules that you excluded. I wonder if those should be removed as well?

**Comment by mjivraja** [comment]
> FYI, there are still these two modules included
> 
> ```
> include::modules/proc_completing-the-rhel7-image.adoc[leveloffset=+1]
> include::modules/proc_completing-the-rhel6-image.adoc[leveloffset=+1]
> ```
> 
> which look related to the two modules that you excluded. I wonder if those should be removed as well?

Those modules belong to Satellite Client, and we keep them unchanged for this PR. ([reference](https://github.com/theforeman/foreman-documentation/pull/1580#discussion_r974043012))

**Review by adamlazik1 — APPROVED** [review]
Understood. In that case, changes look good to me. Merging.

**Comment by adamlazik1** [comment]
Merged to 3.2 and cherry-picked:
fed1766cc..87775a400  3.1 -> 3.1

**Pull request merged**
