### PR TITLE
Fixing columns in the table

### PR DESCRIPTION
**Pull request by jhutar**
The table was rendered incorrectly.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Comment by evgeni** [comment]
@jhutar any reason not to cherry pick this to stable branches?

**Comment by evgeni** [comment]
Ah, I see, 3.3 and older doesn't have this file included.

**Comment by jhutar** [comment]
Thank you Evgeni!

**Comment by ekohl** [comment]
Thanks! This was bothering me too but I forgot to submit a PR.

**Pull request merged**
