### PR TITLE
Change [source,bash] to [source,terminal]

### PR DESCRIPTION
**Pull request by apinnick**
RHSSG guidelines: https://redhat-documentation.github.io/supplementary-style-guide/#code-example-syntax-highlighting

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.9/Katello 4.11 (planned Satellite 6.15)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* We do not accept PRs for Foreman older than 3.3.

### CODE REVIEW

**Comment by maximiliankolb** [comment]
diff looks good; built docs look slightly different:

Screenshot from 2024-02-22 13-55-15
Screenshot from 2024-02-22 13-55-26

I don't think this syntax highlighting was particularly valuable, so I am OK unless there are objections.

**Comment by adamlazik1** [comment]
BTW, the guidelines only talk about not using `source,bash` for terminal commands, but all changed places in this PR are actual bash scripts, where lines starting with `#` should be in interpreted as comments and not as root commands.

**Comment by apinnick** [comment]
@adamlazik1 
This guideline is a general d/s Asciidoc requirement for all blocks with terminal commands, even if they refer to bash scripts. Your comment about the `#` is correct. The issue is not so much the coloring or possible errors. It's more about the fragile nature of our d/s tool chain. A lot of our internal guidelines are intended to enforce uniform Asciidoc so that our publication tools do not break. :-(

**Comment by adamlazik1** [comment]
Well, I don't mind either way, so this PR is fine with me.

**Review by bangelic — COMMENTED** [review]
LGTM

**Comment by adamlazik1** [comment]
Merged and cherry-picked:
   b2e5159957..3cb5aecad3  3.10 -> 3.10
   0336b4a9dd..dec4d737df  3.9 -> 3.9

**Pull request merged**
