### PR TITLE
Add Managing Organizations and Locations to menu

### PR DESCRIPTION
**Pull request by maximiliankolb**
Closes https://github.com/theforeman/foreman-documentation/issues/1165

I don't know if this needs cherry-picking. I assume no.

cc @ekohl

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
This only adds it to landing pages. https://github.com/theforeman/foreman-documentation/blob/master/web/content/js/versions.js is the actual top bar menu.

**Comment by maximiliankolb** [comment]
Thanks for pointing in the right direction.

**Comment by maximiliankolb** [comment]
Rebased to master.

**Review by ekohl — APPROVED** [review]
Thanks!

**Comment by ekohl** [comment]
Test failure looks unrelated, just because the SCAP website timed out.

**Pull request merged**
