### PR TITLE
Fix asciidoc syntax

### LINKED ISSUE #2699: remove "+" sign which is appeared in between "Concurrent registrations use case" and "Remote execution use case" (edit)
Document URL: https://access.redhat.com/documentation/en-us/red_hat_satellite/6.14/html/tuning_performance_of_red_hat_satellite/configuring_project_for_performance_performance-tuning#Smart_Proxy_Configuration_Tuning_performance-tuning

Section Number : 5.9 

Section Name: 
"Concurrent registrations use case" and "Remote execution use case"

Describe the issue: 
remove "+" sign which is appeared in between "Concurrent registrations use case" and "Remote execution use case" these two points comes under the section - "5.9. Capsule Configuration Tuning" - https://access.redhat.com/documentation/en-us/red_hat_satellite/6.14/html-single/tuning_performance_of_red_hat_satellite/index#Smart_Proxy_Configuration_Tuning_performance-tuning

Suggestions for improvement: 

remove + sign

### PR DESCRIPTION
**Pull request by maximiliankolb**
current docs: https://docs.theforeman.org/nightly/Tuning_Performance/index-katello.html#Smart_Proxy_Performance_Tests_performance-tuning

Closes #2699

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
https://osbuild.org/guides/image-builder-on-premises/building-ostree-images.html not being found looks like is a problem because they restructured their whole website. Unrelated to this.

**Comment by Lennonka** [comment]
> https://osbuild.org/guides/image-builder-on-premises/building-ostree-images.html not being found looks like is a problem because they restructured their whole website. Unrelated to this.

Fix filed in PR #2707

**Comment by Lennonka** [comment]
@maximiliankolb No cherrypicks?

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked as far as possible cc @Lennonka 
   b99b1d5a3..474bfacb2  3.9 -> 3.9
   16c87c816..08963d6c4  3.8 -> 3.8
   b7f86e48f..ca059c47e  3.7 -> 3.7
   5e0001da2..4df1fed8c  3.6 -> 3.6
   811775511..8ec2a7fd9  3.5 -> 3.5
   d03de57af..cdbe3fcb8  3.4 -> 3.4
   a8229f022..1a38e4a6c  3.3 -> 3.3

**Pull request merged**
