### PR TITLE
Rework "installing Puppet agent procedure"

### PR DESCRIPTION
**Pull request by maximiliankolb**
This PR extends the procedure to install the Puppet agent and adds it to [Using Puppet for Configuration Management](https://docs.theforeman.org/nightly/Managing_Hosts/index-foreman-el.html#using-puppet-for-configuration-management_managing-hosts).

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Rebased to master.

**Comment by maximiliankolb** [comment]
Are we good here?

**Comment by maximiliankolb** [comment]
Rebased to master. Is this good to go?

**Comment by melcorr** [comment]
Thank you!!

**Pull request merged**
