### PR TITLE
Unify guide title - Tuning

### PR DESCRIPTION
**Pull request by Lennonka**
To make the wording consistent with other titles.

NOTE: This guide is not included in Foreman navigation. Let me know if you want to add it.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.4/Katello 4.6
* [x] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3

### CODE REVIEW

**Review by adamlazik1 — APPROVED** [review]
LGTM

**Review by maximiliankolb — APPROVED** [review]
LGTM

**Comment by adamlazik1** [comment]
Merging.

**Comment by adamlazik1** [comment]
Merged and cherry-picked:
e1b03765c..be090ac26  3.3 -> 3.3
356e57b20..47710e03e  3.4 -> 3.4

**Pull request merged**
