### PR TITLE
correct proxy discovery plugin name

### PR DESCRIPTION
**Pull request by evgeni**
it has been SCLed a few releases ago

### CODE REVIEW

**Comment by evgeni** [comment]
@spetrosi how do cherrypicks to Satellite happen with these new docs?

**Comment by spetrosi** [comment]
> @spetrosi how do cherrypicks to Satellite happen with these new docs?
Hi Evgeni, thank you for your contribution. You changed the package name in all places, I will merge it now.
In the upstream, branches related to downstream have the prefix `SATELLITE-`. Now, these are SATELLITE-6.7, SATELLITE-6.8-beta (no need to cherry-pick to this one because Beta docs are not published now), and SATELLITE-6.8. You need to cherry-pick the changes to the related branches and they will be automatically synced downstream. Usually, I cherry-pick related PRs.

**Comment by spetrosi** [comment]
Do you want me to cherry-pick the changes to 6.7 and 6.8 branches?

**Comment by evgeni** [comment]
@spetrosi this is a 6.8+ only change, so please pick to 6.8.

**Comment by spetrosi** [comment]
Done that

**Pull request merged**
