### PR TITLE
Remove .scssc files from published docs

### PR DESCRIPTION
**Pull request by maximiliankolb**
find . -type f -iname "*.scssc" -exec git rm {} \;

Follow-up PR to https://github.com/theforeman/foreman-documentation/pull/2215 cc @evgeni 

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by evgeni** [comment]
I didn't pick #2215 to any stable branches, so any builds from there will re-introduce those files in the respective directories.

shall we pick it?

**Comment by maximiliankolb** [comment]
Yeah, I think that makes sense. Please cherry-pick up to and including "3.1", and then I'll rebase my branch to drop all unused scssc files.

**Comment by evgeni** [comment]
done

**Review by evgeni — APPROVED** [review]

**Comment by maximiliankolb** [comment]
I have ensure that all branches have built successfully, GHA for gh-page ran, and my branch is on top of the latest commit. I ran the commit command as before.

**Pull request merged**
