### PR TITLE
Show RHCloud plug-in for orcharhino

### PR DESCRIPTION
**Pull request by maximiliankolb**
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [x] Foreman 3.6/Katello 4.8
* [x] Foreman 3.5/Katello 4.7 (Satellite 6.13)

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
It's correct to call it Red Hat Insights because that's the brand name.

I did wonder: would a `{RedHat}` attribute make sense?

**Review by adamlazik1 — APPROVED** [review]
LGTM

**Comment by adamlazik1** [comment]
> I did wonder: would a `{RedHat}` attribute make sense?

For me, yes, because I think attributes can also server as a great way to simplify writing for writers (example: `:PAT: Personal Access Token`). This can also prevent potential errors when when trying to spell out `{nbsp}`.

**Comment by maximiliankolb** [comment]
Yes, I will consider doing this as a follow-up PR soon-ish.

**Comment by maximiliankolb** [comment]
Merged to master and cherry-picked :heavy_check_mark: 
   aba5b0363..858d16ec3  3.7 -> 3.7
   1954f4b2b..e1bae88f4  3.6 -> 3.6
   bc0b8f6fc..5c7fd43a5  3.5 -> 3.5

**Pull request merged**
