### PR TITLE
Improve Puppet introduction 3.2 + cherry-pick fix

### PR DESCRIPTION
**Pull request by Lennonka**
Follow-up to #1147 

The merge conflicts arose because we forgot to cherry-pick a couple of preceding commits. I tried to add them, but I'm not sure how to verify that it's all of them. However, it's without conflicts now and the builds are passing.

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Hey @Lennonka 
I think the assumption that there should not be any merge conflicts because "it's basically the same content" is wrong. 3.2. and 3.1 can be very close together, but it's possible there are commits in 3.2 that should not be backported to 3.1.

Did you resolve any merge conflicts during the cherry-picks? Also, can you please use `git cherry-pick -x COMMIT_ID`, so that the COMMIT_ID is appended to the original commit message. Then it's much easier to validate that you in fact "only" cherry-picked commits from master. This would mean I would not have to review the changes per se because I could verify that they're all coming from master without conflict resolution.

I tested the following and ran into issues:

```
git switch 3.2
git switch -c test
git cherry-pick -x 7e125ca3ff2fc2fef9fc39fde38b3317b104c868
git cherry-pick -x 920766da48d3314e8f480b890ee2281ce16b17b6
git status
git rm guides/common/modules/proc_prerequisites-for-puppet.adoc
git status
git cherry-pick --continue
git cherry-pick -x 065224d05f07bfd745bafebd4e7d0b93646a5934
git cherry-pick --abort
git cherry-pick -x 2b1576e87e0af652f017b8b37caa6cc42cd6a0ba
git remote add lena git@github.com:Lennonka/foreman-documentation.git
git fetch -a
git diff lena/improve-puppet-introduction-3.2
git checkout --track lena/improve-puppet-introduction-3.2
git switch improve-puppet-introduction-3.2
git rebase -i 3.2
```

I still see a diff after rebasing your branch to 3.2:

```
➜  foreman-documentation git:(test) git diff improve-puppet-introduction-3.2
diff --git a/guides/common/assembly_using-puppet-smart-parameters.adoc b/guides/common/assembly_using-puppet-smart-parameters.adoc
index e6c964fc..c210bb1e 100644
--- a/guides/common/assembly_using-puppet-smart-parameters.adoc
+++ b/guides/common/assembly_using-puppet-smart-parameters.adoc
@@ -1,6 +1,6 @@
 ifdef::context[:parent-context: {context}]

-include::modules/con_using-puppet-smart-class-parameters.adoc[leveloffset=+1]
+include::modules/con_using-puppet-smart-parameters.adoc[leveloffset=+1]

 include::modules/ref_puppet-parameter-hierarchy.adoc[leveloffset=+2]

diff --git a/guides/common/modules/con_using-puppet-smart-class-parameters.adoc b/guides/common/modules/con_using-puppet-smart-class-parameters.adoc
deleted file mode 100644
index 6776c7f8..00000000
--- a/guides/common/modules/con_using-puppet-smart-class-parameters.adoc
+++ /dev/null
@@ -1,2 +0,0 @@
-[id="using-puppet-smart-class-parameters_{context}"]
-= Using Puppet Smart Class Parameters
diff --git a/guides/common/modules/con_using-puppet-smart-parameters.adoc b/guides/common/modules/con_using-puppet-smart-parameters.adoc
new file mode 100644
index 00000000..4b479fb2
--- /dev/null
+++ b/guides/common/modules/con_using-puppet-smart-parameters.adoc
@@ -0,0 +1,2 @@
+[id="using-puppet-smart-parameters_{context}"]
+= Using Puppet Smart Class Parameters
```

Did I miss a commit during rebasing? Did you add changes? Right now I don't know where that diff comes from.

**Comment by Lennonka** [comment]
I think you have missed the fifth commit -- https://github.com/theforeman/foreman-documentation/pull/1157/commits/ca0639e7e7121456fc6062009d33c052b2ea7736

**Comment by Lennonka** [comment]
To be honest I don't remember anymore if I was resolving any conflicts during cherry-picikng. It's been a while. I'm sorry.

**Comment by maximiliankolb** [comment]
That was it, then we're good to go!

**Comment by Lennonka** [comment]
@maximiliankolb Thank you so much, Max!

**Pull request merged**
