### PR TITLE
Changing the note in Creating a content view

### PR DESCRIPTION
**Pull request by xzimmerm**
Relevant issue is https://github.com/theforeman/foreman-documentation/issues/1635

I have changed the note into a warning and deleted mentions of the remove option. 
My thought process for removing mentions of Remove is that relevant information about deleting one or multiple versions is [here](https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Deleting_Multiple_Content_View_Versions_content-management), a few chapters below.
I left the mention of Delete because i could not find it mentioned anywhere else in the documentation and changed the paragraph to a Warning, because it seemed more like a warning to the user.

* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4/6.5 on EL8 only)
* We do not accept PRs for Foreman older than 3.3.

### CODE REVIEW

**Review by asteflova — CHANGES_REQUESTED** [review]
https://github.com/theforeman/foreman-documentation/issues/1635 is really about investigating whether the note should even be in the documentation. The key piece of information is in the comment linked from that issue:

> If you create a CV, you're not really in the business of deleting it.

The section with the note is named "Creating a content view". Based on that, I recommend to simply remove the whole ex-NOTE, now-WARNING admonition. Please do that and then update the title and description of your PR to explain the change.

**Comment by xzimmerm** [comment]
Okay, thank you for the clarification.

**Comment by xzimmerm** [comment]
So i have deleted the note entirely because it seemed really out of place. 
But it might be a good idea to open up a new issue on relocating the mention of the Delete option functionality somewhere else.

**Comment by asteflova** [comment]
> So i have deleted the note entirely because it seemed really out of place.
Thank you!

> But it might be a good idea to open up a new issue on relocating the mention of the Delete option functionality somewhere else.
Good point @xzimmerm can you create the issue?

**Review by asteflova — APPROVED** [review]

**Comment by xzimmerm** [comment]
Sure! [Here](https://github.com/theforeman/foreman-documentation/issues/3001) it is. Hope i explained the situation in the issue sufficiently.

**Comment by asteflova** [comment]
Merged to "master" and cherry-picked. On branches 3.8 and lower, I had to resolve a minor conflict.

ee4dbdc27d..039c44d257  3.10 -> 3.10
022aca2053..c38f29591a  3.9 -> 3.9
cd5d83fcb7..3cfc957957  3.8 -> 3.8
363424cf53..fae99cdf27  3.7 -> 3.7
bd46f6c262..69bf633f4f  3.6 -> 3.6
18b1ba1a04..6d8dc1ec51  3.5 -> 3.5
c2bedeb507..ede167490e  3.4 -> 3.4
8e36ecd73a..613780b607  3.3 -> 3.3

**Pull request merged**
