### PR TITLE
[cherry-pick] Feedback for upgrading section

### PR DESCRIPTION
**Pull request by swadeley**
Hello

A cherry-pick from https://github.com/theforeman/foreman-documentation/pull/855

Thank you

### CODE REVIEW

**Comment by lzap** [comment]
Looks like you accidentally pulled some stuff.

**Comment by swadeley** [comment]
@lzap yes, the real problem is there is no 2.5 branch. I 'll try delete this PRs branch.

**Comment by ekohl** [comment]
> @lzap yes, the real problem is there is no 2.5 branch. I 'll try delete this PRs branch.

There is: https://github.com/theforeman/foreman-documentation/tree/2.5 but maybe you don't have one locally?

**Comment by swadeley** [comment]
> > @lzap yes, the real problem is there is no 2.5 branch. I 'll try delete this PRs branch.
> 
> There is: https://github.com/theforeman/foreman-documentation/tree/2.5 but maybe you don't have one locally?

Yes, sorry, I forgot to add 'upstream` when I did `git fetch`, got it now

**Comment by swadeley** [comment]
Hello, please review now, thank you.

**Review by ekohl — CHANGES_REQUESTED** [review]
There are various merge conflicts in the file.

**Review by ekohl — APPROVED** [review]

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
