### PR TITLE
Do not split sentences with code blocks

### PR DESCRIPTION
**Pull request by maximiliankolb**
This PR is an extension to https://github.com/theforeman/foreman-documentation/pull/808. I feel like I gave bad advice to @calvingsmith.

### CODE REVIEW

**Comment by maximiliankolb** [comment]
Apparently it has already been cherry-picked to 2.5: https://github.com/theforeman/foreman-documentation/pull/826 Once merged, I will create a new PR against 2.5.

**Comment by maximiliankolb** [comment]
Rebased to master.

**Review by lzap — APPROVED** [review]
My bad, apologies @maximiliankolb for taking over. I am trying to unblock RHD as much as possible in these tough times. Thank you looks reasonable.

**Comment by maximiliankolb** [comment]
Thanks @lzap. I've got a new PR against 2.5: https://github.com/theforeman/foreman-documentation/pull/843

**Pull request merged**
