### PR TITLE
Debian Installation guides

### PR DESCRIPTION
**Pull request by melcorr**
As part of

Bug 1803033 - [upstream] add Installing Foreman on Debian system guide.

https://bugzilla.redhat.com/show_bug.cgi?id=1803033

### CODE REVIEW

**Comment by melcorr** [comment]
Hi @lzap 
I applied all @Baboon92's feedback. He and I were emailing a but. It took me a long time to get to do this with transitioning into my new job.. 
I noticed there was no upstream installation step for the external Smart Proxy, so I added that step. It might not need the puppet options so please let me know. 
Thanks, 
Melanie

**Comment by melcorr** [comment]
Changing the reviewer to @tahliar as she is blocked on additional work because of these changes.

**Comment by lzap** [comment]
Sorry for the delay, looking into this. I have only deployed Foreman on Debian few times long time ago, will do my best to find gaps tho.

**Comment by lzap** [comment]
Nitpick: The main title says "Installing Foreman server", I'd expect to have "on Debian" or similar.

**Comment by lzap** [comment]
I have reviewed both Server and Capsule builds for Debian. Attached via email.

**Pull request merged**
