### PR TITLE
Drop proc on configuring cross-forest trust in FreeIPA

### PR DESCRIPTION
**Pull request by asteflova**
https://github.com/theforeman/foreman-documentation/pull/2938 split an assembly on configuring Active Directory as an external authentication source into two assemblies: One for indirect integration through FreeIPA, the other for direct integration through SSSD+Samba Winbind. However, I overlooked one procedure that should have been dropped completely. This PR addresses that oversight.

The module that I propose to remove, `guides/common/modules/proc_configuring-the-freeipa-server-to-use-cross-forest-trust.adoc`, explains how to configure a cross-forest trust between FreeIPA and AD. However, as `guides/common/modules/con_configuring-freeipa-server-as-an-external-identity-provider-for-project.adoc` explains, the only thing you need to do on the Foreman side is to configure FreeIPA as an external authentication source.

The cross-forest trust is actually configured on the FreeIPA's side, using FreeIPA's tools by a FreeIPA administrator, and no other action needs to be taken on the Foreman side.

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [x] Foreman 3.11/Katello 4.13
* [ ] Foreman 3.10/Katello 4.12
* [ ] Foreman 3.9/Katello 4.11 (Satellite 6.15; orcharhino 6.8/6.9)
* [ ] Foreman 3.8/Katello 4.10
* [ ] Foreman 3.7/Katello 4.9 (Satellite 6.14)
* [ ] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13; orcharhino 6.6/6.7)
* We do not accept PRs for Foreman older than 3.5.

### CODE REVIEW

**Comment by domiborges** [comment]
Hi @asteflova , I totally agree with removing this content. All the steps are performed on the ipa side so it's better to refer to ipa docs instead. Plus you don't have to worry about keeping it up to date.

**Review by maximiliankolb — COMMENTED** [review]
Your PR only removes content. Is the link to the primary docs already part of Foreman docs?

**Comment by asteflova** [comment]
> Your PR only removes content. Is the link to the primary docs already part of Foreman docs?

To be honest, I didn't think it was necessary. On the Foreman side, all you should need to know is that when a cross-forest trust with AD is in place, AD users will be able to log in (we do mention this). But it might be a good idea to share a link.

Let's try to do that consistently for the other authentication projects as well: https://github.com/theforeman/foreman-documentation/pull/3208. This PR adds a link to the FreeIPA/RHEL IdM planning guide and mentions the cross-forest trust feature.

**Comment by apinnick** [comment]
@asteflova Is this ready to merge?

**Comment by asteflova** [comment]
> @asteflova Is this ready to merge?

It is... as long as I can interpret Max's thumbs-up and your question as acks.

**Comment by asteflova** [comment]
Merged and "cherry-picked":

ebc47f0cb9..19a5bf13ae  3.11 -> 3.11

**Pull request merged**
