### PR TITLE
Remove steps required for EL 7 from the upgrade steps

### PR DESCRIPTION
**Pull request by AkshayGadhaveRH**
The last two versions of Ptoject are only supported on EL 8. Removing the steps to configure Ansible and Software Collections repositories from the steps to upgrade disconnected systems. These steps are only required for EL 7 systems.

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.5/Katello 4.7 (planned Satellite 6.13)
* [X] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only)
* [ ] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [ ] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8, orcharhino 6.2 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Comment by AkshayGadhaveRH** [comment]
@evgeni does this look good? I'll push separate PRs for the other branches as F3.3 works with EL7 systems as well.

**Review by maximiliankolb — APPROVED** [review]
Change LGTM; can someone else confirm?

**Review by evgeni — APPROVED** [review]
This can be also safely picked to 3.3 as this file only affects Satellite and Satellite 6.12 (based on 3.3) does *not* support EL7 either.

Only 3.1/Sat 6.11 needs special handling.

**Comment by adamlazik1** [comment]
Merged and cherry-picked:
   449c54e25..3fd2d4a35  3.3 -> 3.3
   2406b198d..1a41bc444  3.4 -> 3.4
   da6514c7a..2c9d9bd14  3.5 -> 3.5

**Pull request merged**
