### PR TITLE
Restructure content management guide part 1

### PR DESCRIPTION
**Pull request by maximiliankolb**
This PR restructures the content management guide. The goal is having exactly one heading per file. It also removes unnecessary whitespace here and there.

I did **not** make (substancial) changes to the actual text, so please wait for this to get merged and then open a PR/raise an issue against master. I will do my best with incorporating any suggestions, however, this PR does not change status quo.

### CODE REVIEW

**Comment by melcorr** [comment]
Thank you @maximiliankolb  - this is on my TODO list. 
It might take me until early next week to test.

**Comment by maximiliankolb** [comment]
Rebased to master.

I propose you review the diff of the output to the master branch:

1. Build docs on master locally
2. `cp guides/build/Content_Management_Guide/index-foreman-el.html /tmp/cmg_master.html`
3. Builds docs on this branch locally
4. `cp guides/build/Content_Management_Guide/index-foreman-el.html /tmp/cmg_feature.html`
5. `diff /tmp/cmg_master.html /tmp/cmg_feature.html`

**Comment by maximiliankolb** [comment]
Reviewed the diff by hand & fixed one issue where a heading was not set properly (`==` instead of `=`). Thanks @louisrokitta.

**Comment by melcorr** [comment]
> Rebased to master.
> 
> I propose you review the diff of the output to the master branch:
> 
>     1. Build docs on master locally
> 
>     2. `cp guides/build/Content_Management_Guide/index-foreman-el.html /tmp/cmg_master.html`
> 
>     3. Builds docs on this branch locally
> 
>     4. `cp guides/build/Content_Management_Guide/index-foreman-el.html /tmp/cmg_feature.html`
> 
>     5. `diff /tmp/cmg_master.html /tmp/cmg_feature.html`

In general, I use meld :)

**Review by melcorr — APPROVED** [review]
I went through this and cannot find fault. 
Thank you. I know this work is a PITA.

**Pull request merged**
