### PR TITLE
Drop umask system requirement

### PR DESCRIPTION
**Pull request by mjivraja**
https://projects.theforeman.org/issues/35138

* [X] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [X] Foreman 3.7/Katello 4.9 (planned Satellite 6.14)
* [X] Foreman 3.6/Katello 4.8
* [ ] Foreman 3.5/Katello 4.7 (Satellite 6.13)
* [ ] Foreman 3.4/Katello 4.6 (EL8 only)
* [ ] Foreman 3.3/Katello 4.5 on EL7 & EL8 (Satellite 6.12 on EL8 only; orcharhino 6.4 on EL8 only)
* [ ] Foreman 3.2/Katello 4.4 on EL7 & EL8
* [ ] Foreman 3.1/Katello 4.3 on EL7 & EL8 (Satellite 6.11 EL7/8; orcharhino 6.3 on EL7/8)
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.4 or older.

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
While the change is good, it's better to use `git revert 1427fd2e39d6f6a025c02c1b56bb53fd16e11601` as the command. That nicely ties it back to the commit that introduced the regression.

**Review by adamlazik1 — APPROVED** [review]
+1 to Ewoud's suggestion, the change looks good. Once the revert commit is applied this is good to go.

**Comment by mjivraja** [comment]
> While the change is good, it's better to use `git revert 1427fd2e39d6f6a025c02c1b56bb53fd16e11601` as the command. That nicely ties it back to the commit that introduced the regression.

I am unable to revert this commit 😐 Don't know the reason as there is no error or info displayed. However, I am able to revert other commits.

Can we try any other way?

**Comment by adamlazik1** [comment]
I went ahead and reverted this on master and 3.7 and 3.6 branches. Are those the only branches where this needs to be reverted @ekohl?

**Comment by mjivraja** [comment]
> @mjivraja did you reset your commit? It's likely it can't revert because your commit already does the same. Without the command output I can only guess.
> 
> @adamlazik1 the Redmine says it was fixed in 3.4.0 I'd say the 3.4 & 3.5 branches also need the revert.

Ahh yes, I didn't reset the commit assuming the new revert commit will be on top. Thanks @ekohl :rocket:

**Comment by adamlazik1** [comment]
I also reverted on 3.5 and 3.4 seems to not have the change in the first place. All changes are upstream so this PR can be safely closed.

**Comment by mjivraja** [comment]
> I also reverted on 3.5 and 3.4 seems to not have the change in the first place. All changes are upstream so this PR can be safely closed.

Owwk. Thanks @adamlazik1 @ekohl 
Closing this PR.

**Pull request closed without merging**
