### PR TITLE
Set satellite attributes for version 6.13

### PR DESCRIPTION
**Pull request by mdolezelova**
* [ ] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into:

* [ ] Foreman 3.5/Katello 4.7
* [ ] Foreman 3.4/Katello 4.6
* [ ] Foreman 3.3/Katello 4.5
* [ ] Foreman 3.2/Katello 4.4
* [ ] Foreman 3.1/Katello 4.3
* For Foreman 3.0 or older, please create a separate PR.
* We do not accept PRs for Foreman 2.3 or older.

### CODE REVIEW

**Comment by adamlazik1** [comment]
Thanks for the PR!
I am waiting for 6.13 link to be added in linkchecker.ini before merging this to avoid linkchecker errors. It should be done in #1815.
FYI, I will merge this to master from where it will be cherry-picked to 3.5.

**Review by ekohl — CHANGES_REQUESTED** [review]
Like @adamlazik1 said, please first to master. Then please also add 6.13 to linkchecker.ini.

**Comment by mdolezelova** [comment]
Hi @adamlazik1 , please is there any AI for me or do I just need to wait for this to be merged? I've raised it only against the branch 3.5 intentionally, because it is just a change of Satellite attributes that is only relevant for 3.5 and not for master. Thank you!

**Comment by adamlazik1** [comment]
Hey @mdolezelova,
For now it would be best to just wait since there already is one PR to add 6.13 to linkchecker.ini. Hopefully it gets resolved soon.
>  I've raised it only against the branch 3.5 intentionally, because it is just a change of Satellite attributes that is only relevant for 3.5 and not for master. 

I understand that, however we (almost) always make the changes against master when they are concerning the newest release branch and then cherry-pick to that branch. This is to minimize merge conflicts. The version will be replaced again when there is newer branch than the current newest branch.

**Comment by adamlazik1** [comment]
Re-running checks since #1815 got merged.

**Comment by adamlazik1** [comment]
Ugh, I see it's not as easy as changing the base branch. Please run `git rebase --onto master 3.5`, then change the base branch to master so we can merge this to master and cherry-pick to 3.5.

**Comment by ekohl** [comment]
FYI: I think f35747971617d678adebc4741c1c9dc5be5dc79d should have been part of the bump to 6.13 in attributes. That should have been one atomic commit.

**Comment by adamlazik1** [comment]
My apologies. I understood that incorrectly.

**Comment by adamlazik1** [comment]
After agreement with @mdolezelova I am closing this PR and opening a new one against master with replicated changes.

**Pull request closed without merging**
