### PR TITLE
Simplify enable and sync the Client repo for Satellite

### PR DESCRIPTION
**Pull request by Lennonka**
I think that it's enough to only give generic hints to the user instead of providing a procedure for each RHEL version. Additionally, the repo is provided also for other architectures than just x86_64. I was hoping to provide a table of all Satellite Client 6 repo variants, however, this list is much longer than I anticipated (see the first comment). In the end, I decided to leave the repo names out altogether.

I've also decided not to include CLI procedures, because the naming of the repositories and architectures is inconsistent. I wouldn't recommend to do these tasks in the CLI, because the CLI by itself doesn't provide sufficient data to support it. However, if we would be okay with x86_64 arch as an example, I'm happy to re-add the CLI procedures.

* [x] I am okay with my commits getting squashed when you merge this PR.
* [x] I am familiar with the [contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) guidelines.

Please cherry-pick my commits into: no cherry-picks

### CODE REVIEW

**Comment by Lennonka** [comment]
List of all available Client repos:

```
# hammer repository-set list --organization "Default Organization" --search "Satellite Client" \
--fields name | grep "(RPMs)" | grep "Satellite Client"

Red Hat Satellite Client 6 (for RHEL 6 for System Z - ELS) (RPMs)                                           
Red Hat Satellite Client 6 (for RHEL 6 Server - ELS) (RPMs)                                                 
Red Hat Satellite Client 6 (for RHEL 7 Desktop) (RPMs)                                                      
Red Hat Satellite Client 6 (for RHEL 7 for IBM Power LE) (RPMs)                                             
Red Hat Satellite Client 6 (for RHEL 7 for IBM Power LE - Update Services for SAP Solutions) (RPMs)         
Red Hat Satellite Client 6 (for RHEL 7 for IBM Power) (RPMs)                                                
Red Hat Satellite Client 6 (for RHEL 7 for Scientific Computing) (RPMs)                                     
Red Hat Satellite Client 6 (for RHEL 7 for System Z) (RPMs)                                                 
Red Hat Satellite Client 6 (for RHEL 7 Server - AUS) (RPMs)                                                 
Red Hat Satellite Client 6 (for RHEL 7 Server) (RPMs)                                                       
Red Hat Satellite Client 6 (for RHEL 7 Server - TUS) (RPMs)                                                 
Red Hat Satellite Client 6 (for RHEL 7 Server - Update Services for SAP Solutions) (RPMs)                   
Red Hat Satellite Client 6 (for RHEL 7 Workstation) (RPMs)                                                  
Red Hat Satellite Client 6 for RHEL 8 aarch64 (RPMs)                                                        
Red Hat Satellite Client 6 for RHEL 8 IBM z Systems - Extended Update Support (RPMs)                        
Red Hat Satellite Client 6 for RHEL 8 Power, little endian - Extended Update Support (RPMs)                 
Red Hat Satellite Client 6 for RHEL 8 Power, little endian - Update Services for SAP Solutions (RPMs)       
Red Hat Satellite Client 6 for RHEL 8 ppc64le (RPMs)                                                        
Red Hat Satellite Client 6 for RHEL 8 s390x (RPMs)                                                          
Red Hat Satellite Client 6 for RHEL 8 x86_64 - Advanced Mission Critical Update Support (RPMs)              
Red Hat Satellite Client 6 for RHEL 8 x86_64 - Extended Update Support (RPMs)                               
Red Hat Satellite Client 6 for RHEL 8 x86_64 (RPMs)                                                         
Red Hat Satellite Client 6 for RHEL 8 x86_64 - Telecommunications Update Service (RPMs)                     
Red Hat Satellite Client 6 for RHEL 8 x86_64 - Update Services for SAP Solutions (RPMs)                     
Red Hat Satellite Client 6 for RHEL 9 aarch64 (RPMs)                                                        
Red Hat Satellite Client 6 for RHEL 9 IBM z Systems - Extended Update Support (RPMs)                        
Red Hat Satellite Client 6 for RHEL 9 Power, little endian - Extended Update Support (RPMs)                 
Red Hat Satellite Client 6 for RHEL 9 Power, little endian - Update Services for SAP Solutions (RPMs)       
Red Hat Satellite Client 6 for RHEL 9 ppc64le (RPMs)                                                        
Red Hat Satellite Client 6 for RHEL 9 s390x (RPMs)                                                          
Red Hat Satellite Client 6 for RHEL 9 x86_64 - Advanced Mission Critical Update Support (RPMs)              
Red Hat Satellite Client 6 for RHEL 9 x86_64 - Extended Update Support (RPMs)                               
Red Hat Satellite Client 6 for RHEL 9 x86_64 (RPMs)                                                         
Red Hat Satellite Client 6 for RHEL 9 x86_64 - Update Services for SAP Solutions (RPMs) ```

**Review by maximiliankolb — COMMENTED** [review]
Two small comments; please also delete unused modules from guides/common/assembly_enabling-and-synchronizing-the-project-client-name-repository.adoc; rest LGTM.

**Comment by Lennonka** [comment]
@maximiliankolb The assembly is included only for Satellite, so there's no need for additional conditions. My bad, I forgot to indicate. I've removed the unused files, thank you for the reminder!

**Comment by Lennonka** [comment]
I had to add a new solution using ISS for the disconnected env, because RH CP doesn't provide ISOs for this repo.

**Review by maximiliankolb — APPROVED** [review]
diff LGTM.

Not blocking your PR: I wonder why we don't include these procedures for Katello and orcharhino. With a tiny adjustment about the delivered packages in the Client repo, we could probably make this work in a future PR.

**Comment by Lennonka** [comment]
@maximiliankolb There's a huge mess in Installing guides if you meant including it there.

**Comment by maximiliankolb** [comment]
> @maximiliankolb There's a huge mess in Installing guides for upstream if you meant including it there. 😆

Thanks for the warning ... then I won't try. :D

**Pull request merged**
